package OOP;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GUI extends javax.swing.JFrame {

    private Order currentOrder = new Order();
    
    java.sql.Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    public GUI() {
        initComponents();
        con = db.myCon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        btExit = new javax.swing.JButton();
        lbCake = new javax.swing.JLabel();
        lbDrink = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        Drink = new javax.swing.JPanel();
        dContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pIGreenTea = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        addIGreenTea = new javax.swing.JButton();
        qtyIGreenTea = new javax.swing.JSpinner();
        pICappuccino = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        addICappuccino = new javax.swing.JButton();
        qtyICappuccino = new javax.swing.JSpinner();
        pILatte = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        addILatte = new javax.swing.JButton();
        qtyILatte = new javax.swing.JSpinner();
        pIAmericano = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        addIAmericano = new javax.swing.JButton();
        qtyIAmericano = new javax.swing.JSpinner();
        pHLatte = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        addHLatte = new javax.swing.JButton();
        qtyHLatte = new javax.swing.JSpinner();
        pHCappuccino = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        addHCappuccino = new javax.swing.JButton();
        qtyHCappuccino = new javax.swing.JSpinner();
        pHGreenTea = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        addHGreenTea = new javax.swing.JButton();
        qtyHGreenTea = new javax.swing.JSpinner();
        pHEspresso = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        addHEspresso = new javax.swing.JButton();
        qtyHEspresso = new javax.swing.JSpinner();
        Cake = new javax.swing.JPanel();
        cContainer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        right = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbSubtotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbDiscount = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JTextField();
        btTotal = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btSubtotal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1512, 982));
        getContentPane().setLayout(null);

        sidePanel.setBackground(new java.awt.Color(255, 255, 255));
        sidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 36, 23)));
        sidePanel.setLayout(null);

        btExit.setText("Exit");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        sidePanel.add(btExit);
        btExit.setBounds(40, 860, 72, 40);

        lbCake.setBackground(new java.awt.Color(229, 214, 192));
        lbCake.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 12)); // NOI18N
        lbCake.setForeground(new java.awt.Color(51, 51, 51));
        lbCake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCake.setText("Cake");
        lbCake.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(50, 36, 23), 1, true));
        lbCake.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbCake.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbCake.setOpaque(true);
        lbCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCakeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCakeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCakeMouseExited(evt);
            }
        });
        sidePanel.add(lbCake);
        lbCake.setBounds(0, 240, 160, 60);

        lbDrink.setBackground(new java.awt.Color(229, 214, 192));
        lbDrink.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 12)); // NOI18N
        lbDrink.setForeground(new java.awt.Color(51, 51, 51));
        lbDrink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDrink.setText("Drink ");
        lbDrink.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(50, 36, 23), 1, true));
        lbDrink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbDrink.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbDrink.setOpaque(true);
        lbDrink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDrinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbDrinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbDrinkMouseExited(evt);
            }
        });
        sidePanel.add(lbDrink);
        lbDrink.setBounds(0, 180, 160, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOP/image 10.png"))); // NOI18N
        sidePanel.add(jLabel6);
        jLabel6.setBounds(20, 30, 120, 120);

        getContentPane().add(sidePanel);
        sidePanel.setBounds(0, 0, 160, 980);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 36, 23)));
        body.setLayout(new java.awt.CardLayout());

        Drink.setLayout(null);

        dContainer.setBackground(new java.awt.Color(245, 245, 245));
        dContainer.setLayout(null);

        jLabel1.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jLabel1.setText("Caffeine");
        dContainer.add(jLabel1);
        jLabel1.setBounds(30, 50, 110, 30);
        dContainer.add(jSeparator1);
        jSeparator1.setBounds(30, 80, 110, 3);

        pIGreenTea.setBackground(new java.awt.Color(255, 255, 255));
        pIGreenTea.setLayout(null);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOP/image 2.png"))); // NOI18N
        pIGreenTea.add(jLabel10);
        jLabel10.setBounds(20, 0, 150, 150);

        jLabel17.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel17.setText("1.5$");
        pIGreenTea.add(jLabel17);
        jLabel17.setBounds(10, 180, 40, 16);

        jLabel18.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel18.setText("Iced Green Tea");
        pIGreenTea.add(jLabel18);
        jLabel18.setBounds(10, 160, 120, 16);

        addIGreenTea.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addIGreenTea.setText("ADD");
        addIGreenTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIGreenTeaActionPerformed(evt);
            }
        });
        pIGreenTea.add(addIGreenTea);
        addIGreenTea.setBounds(130, 160, 60, 60);

        qtyIGreenTea.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pIGreenTea.add(qtyIGreenTea);
        qtyIGreenTea.setBounds(10, 200, 64, 20);

        dContainer.add(pIGreenTea);
        pIGreenTea.setBounds(280, 620, 200, 240);

        pICappuccino.setBackground(new java.awt.Color(255, 255, 255));
        pICappuccino.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOP/image 4.png"))); // NOI18N
        pICappuccino.add(jLabel8);
        jLabel8.setBounds(20, 0, 150, 150);

        jLabel13.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel13.setText("2.0$");
        pICappuccino.add(jLabel13);
        jLabel13.setBounds(10, 180, 40, 16);

        jLabel14.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel14.setText("Iced Cappuccino");
        pICappuccino.add(jLabel14);
        jLabel14.setBounds(10, 160, 120, 16);

        addICappuccino.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addICappuccino.setText("ADD");
        addICappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addICappuccinoActionPerformed(evt);
            }
        });
        pICappuccino.add(addICappuccino);
        addICappuccino.setBounds(130, 160, 60, 60);

        qtyICappuccino.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pICappuccino.add(qtyICappuccino);
        qtyICappuccino.setBounds(10, 200, 64, 20);

        dContainer.add(pICappuccino);
        pICappuccino.setBounds(50, 620, 200, 240);

        pILatte.setBackground(new java.awt.Color(255, 255, 255));
        pILatte.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOP/image 1.png"))); // NOI18N
        pILatte.add(jLabel7);
        jLabel7.setBounds(20, 0, 150, 150);

        jLabel11.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel11.setText("2.0$");
        pILatte.add(jLabel11);
        jLabel11.setBounds(10, 180, 40, 16);

        jLabel12.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel12.setText("Iced Latte");
        pILatte.add(jLabel12);
        jLabel12.setBounds(10, 160, 80, 16);

        addILatte.setText("ADD");
        addILatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addILatteActionPerformed(evt);
            }
        });
        pILatte.add(addILatte);
        addILatte.setBounds(130, 160, 60, 60);

        qtyILatte.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pILatte.add(qtyILatte);
        qtyILatte.setBounds(10, 200, 64, 20);

        dContainer.add(pILatte);
        pILatte.setBounds(280, 360, 200, 240);

        pIAmericano.setBackground(new java.awt.Color(255, 255, 255));
        pIAmericano.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOP/image 3.png"))); // NOI18N
        pIAmericano.add(jLabel9);
        jLabel9.setBounds(20, 0, 150, 150);

        jLabel15.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel15.setText("1.5$");
        pIAmericano.add(jLabel15);
        jLabel15.setBounds(10, 180, 40, 16);

        jLabel16.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel16.setText("Iced Americano");
        pIAmericano.add(jLabel16);
        jLabel16.setBounds(10, 160, 110, 16);

        addIAmericano.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addIAmericano.setText("ADD");
        addIAmericano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIAmericanoActionPerformed(evt);
            }
        });
        pIAmericano.add(addIAmericano);
        addIAmericano.setBounds(130, 160, 60, 60);

        qtyIAmericano.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pIAmericano.add(qtyIAmericano);
        qtyIAmericano.setBounds(10, 200, 64, 20);

        dContainer.add(pIAmericano);
        pIAmericano.setBounds(510, 360, 200, 240);

        pHLatte.setBackground(new java.awt.Color(255, 255, 255));
        pHLatte.setLayout(null);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOP/98d03bd7c2a93f2e4f9972efa9da61be.png"))); // NOI18N
        pHLatte.add(jLabel25);
        jLabel25.setBounds(20, 0, 150, 150);

        jLabel26.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel26.setText("1,5$");
        pHLatte.add(jLabel26);
        jLabel26.setBounds(10, 180, 40, 16);

        jLabel27.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel27.setText("Hot Latte");
        pHLatte.add(jLabel27);
        jLabel27.setBounds(10, 160, 80, 16);

        addHLatte.setText("ADD");
        addHLatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHLatteActionPerformed(evt);
            }
        });
        pHLatte.add(addHLatte);
        addHLatte.setBounds(130, 160, 60, 60);

        qtyHLatte.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pHLatte.add(qtyHLatte);
        qtyHLatte.setBounds(10, 200, 64, 20);

        dContainer.add(pHLatte);
        pHLatte.setBounds(50, 100, 200, 240);

        pHCappuccino.setBackground(new java.awt.Color(255, 255, 255));
        pHCappuccino.setLayout(null);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOP/46e2af89e9d690dd555be8a7e486bb96.png"))); // NOI18N
        pHCappuccino.add(jLabel22);
        jLabel22.setBounds(20, 0, 150, 150);

        jLabel23.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel23.setText("1.5$");
        pHCappuccino.add(jLabel23);
        jLabel23.setBounds(10, 180, 40, 16);

        jLabel24.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel24.setText("Hot Cappuccino");
        pHCappuccino.add(jLabel24);
        jLabel24.setBounds(10, 160, 120, 16);

        addHCappuccino.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addHCappuccino.setText("ADD");
        addHCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHCappuccinoActionPerformed(evt);
            }
        });
        pHCappuccino.add(addHCappuccino);
        addHCappuccino.setBounds(130, 160, 60, 60);

        qtyHCappuccino.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pHCappuccino.add(qtyHCappuccino);
        qtyHCappuccino.setBounds(10, 200, 64, 20);

        dContainer.add(pHCappuccino);
        pHCappuccino.setBounds(510, 100, 200, 240);

        pHGreenTea.setBackground(new java.awt.Color(255, 255, 255));
        pHGreenTea.setLayout(null);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOP/73745cbf117bac2f7bd80a018767976b.png"))); // NOI18N
        pHGreenTea.add(jLabel19);
        jLabel19.setBounds(20, 0, 150, 150);

        jLabel20.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel20.setText("1.5$");
        pHGreenTea.add(jLabel20);
        jLabel20.setBounds(10, 180, 40, 16);

        jLabel21.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel21.setText("Hot Green Tea");
        pHGreenTea.add(jLabel21);
        jLabel21.setBounds(10, 160, 120, 16);

        addHGreenTea.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addHGreenTea.setText("ADD");
        addHGreenTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHGreenTeaActionPerformed(evt);
            }
        });
        pHGreenTea.add(addHGreenTea);
        addHGreenTea.setBounds(130, 160, 60, 60);

        qtyHGreenTea.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pHGreenTea.add(qtyHGreenTea);
        qtyHGreenTea.setBounds(10, 200, 64, 20);

        dContainer.add(pHGreenTea);
        pHGreenTea.setBounds(50, 360, 200, 240);

        pHEspresso.setBackground(new java.awt.Color(255, 255, 255));
        pHEspresso.setLayout(null);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/OOP/d6600f2db33c4ccad883a646531c8b23.png"))); // NOI18N
        pHEspresso.add(jLabel28);
        jLabel28.setBounds(20, 0, 150, 150);

        jLabel29.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel29.setText("1.0$");
        pHEspresso.add(jLabel29);
        jLabel29.setBounds(10, 180, 40, 16);

        jLabel30.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel30.setText("Hot Espresso");
        pHEspresso.add(jLabel30);
        jLabel30.setBounds(10, 160, 110, 16);

        addHEspresso.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addHEspresso.setText("ADD");
        addHEspresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHEspressoActionPerformed(evt);
            }
        });
        pHEspresso.add(addHEspresso);
        addHEspresso.setBounds(130, 160, 60, 60);

        qtyHEspresso.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pHEspresso.add(qtyHEspresso);
        qtyHEspresso.setBounds(10, 200, 64, 20);

        dContainer.add(pHEspresso);
        pHEspresso.setBounds(280, 100, 200, 240);

        Drink.add(dContainer);
        dContainer.setBounds(0, 0, 750, 980);

        body.add(Drink, "card2");

        Cake.setLayout(null);

        cContainer.setBackground(new java.awt.Color(255, 255, 255));
        cContainer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), -1));
        cContainer.setLayout(null);

        jLabel2.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jLabel2.setText("Cake");
        cContainer.add(jLabel2);
        jLabel2.setBounds(30, 50, 64, 30);
        cContainer.add(jSeparator2);
        jSeparator2.setBounds(30, 80, 60, 3);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        cContainer.add(jPanel9);
        jPanel9.setBounds(30, 110, 170, 210);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        cContainer.add(jPanel10);
        jPanel10.setBounds(230, 110, 170, 210);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        cContainer.add(jPanel11);
        jPanel11.setBounds(430, 110, 170, 210);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        cContainer.add(jPanel13);
        jPanel13.setBounds(30, 340, 170, 210);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        cContainer.add(jPanel15);
        jPanel15.setBounds(230, 340, 170, 210);

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        cContainer.add(jPanel16);
        jPanel16.setBounds(430, 340, 170, 210);

        Cake.add(cContainer);
        cContainer.setBounds(0, 0, 750, 980);

        body.add(Cake, "card3");

        getContentPane().add(body);
        body.setBounds(160, 0, 750, 980);

        right.setBackground(new java.awt.Color(255, 255, 255));
        right.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(50, 36, 3)));
        right.setLayout(null);

        table.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Price", "Qty", "Customization", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table);

        right.add(jScrollPane2);
        jScrollPane2.setBounds(10, 20, 580, 390);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(null);

        jLabel3.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        jLabel3.setText("Discount: ");
        jPanel17.add(jLabel3);
        jLabel3.setBounds(20, 60, 130, 30);

        lbSubtotal.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        lbSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbSubtotalActionPerformed(evt);
            }
        });
        jPanel17.add(lbSubtotal);
        lbSubtotal.setBounds(160, 10, 190, 30);

        jLabel4.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        jLabel4.setText("Subtotal: ");
        jPanel17.add(jLabel4);
        jLabel4.setBounds(20, 10, 119, 30);

        cbDiscount.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        cbDiscount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "30%", "50%", "70%" }));
        cbDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDiscountActionPerformed(evt);
            }
        });
        jPanel17.add(cbDiscount);
        cbDiscount.setBounds(160, 60, 190, 30);

        jLabel5.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        jLabel5.setText("Total:");
        jPanel17.add(jLabel5);
        jLabel5.setBounds(20, 110, 59, 25);

        lbTotal.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        lbTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbTotalActionPerformed(evt);
            }
        });
        jPanel17.add(lbTotal);
        lbTotal.setBounds(160, 110, 190, 28);

        right.add(jPanel17);
        jPanel17.setBounds(20, 430, 370, 150);

        btTotal.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        btTotal.setText("Total");
        btTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTotalActionPerformed(evt);
            }
        });
        right.add(btTotal);
        btTotal.setBounds(190, 620, 130, 40);

        btDelete.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        right.add(btDelete);
        btDelete.setBounds(430, 440, 130, 30);

        btSubtotal.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        btSubtotal.setText("Subtotal");
        btSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubtotalActionPerformed(evt);
            }
        });
        right.add(btSubtotal);
        btSubtotal.setBounds(40, 620, 130, 40);

        getContentPane().add(right);
        right.setBounds(910, 0, 600, 980);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCakeMouseClicked
        body.removeAll();
        body.add(Cake);
        body.revalidate();
        body.repaint();
    }//GEN-LAST:event_lbCakeMouseClicked

    private void lbDrinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDrinkMouseClicked
        body.removeAll();
        body.add(Drink);
        body.revalidate();
        body.repaint();
    }//GEN-LAST:event_lbDrinkMouseClicked

    private void lbDrinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDrinkMouseExited
        lbDrink.setBackground(new Color(229,214,192));
    }//GEN-LAST:event_lbDrinkMouseExited

    private void lbDrinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDrinkMouseEntered
        lbDrink.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_lbDrinkMouseEntered

    private void lbCakeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCakeMouseEntered
        lbCake.setBackground(new Color(204,204,204));
    }//GEN-LAST:event_lbCakeMouseEntered

    private void lbCakeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCakeMouseExited
        lbCake.setBackground(new Color(229,214,192));
    }//GEN-LAST:event_lbCakeMouseExited

    private void lbSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSubtotalActionPerformed

    private void lbTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbTotalActionPerformed

    private void addILatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addILatteActionPerformed
        addToCart("D05", "Iced Latte", qtyILatte);
    }//GEN-LAST:event_addILatteActionPerformed

    private void addICappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addICappuccinoActionPerformed
        addToCart("D07", "Iced Cappuccino", qtyICappuccino);
    }//GEN-LAST:event_addICappuccinoActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int selectedRow = table.getSelectedRow();

        // 1. Check if the user actually clicked a row
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an item to delete.", "Delete Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Remove from the Logic (Order.java)
        // IMPORTANT: This must happen while the indexes still match!
        currentOrder.removeProduct(selectedRow);

        // 3. Remove from the View (JTable)
        model.removeRow(selectedRow);

        // Optional: Clear the Total label since the previous total is now wrong
        lbTotal.setText(""); 
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTotalActionPerformed
        // 1. Ask Order logic for the final price (it automatically applies the discount)
        double finalTotal = currentOrder.calculateTotal();

        // 2. Display it
        lbTotal.setText(String.format("$%.2f", finalTotal));

        // 3. Ask for Payment Confirmation
        int choice = JOptionPane.showConfirmDialog(this, 
                "Total Amount: " + String.format("$%.2f", finalTotal) + "\nProceed to payment?", 
                "Checkout", 
                JOptionPane.YES_NO_OPTION);

        // 4. If Yes, Save to Database
        if (choice == JOptionPane.YES_OPTION) {
            saveOrderToDatabase(finalTotal);
        }
    }//GEN-LAST:event_btTotalActionPerformed

    private void cbDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDiscountActionPerformed
        // Get the selected discount percentage from the ComboBox
        String selectedDiscount = (String) cbDiscount.getSelectedItem();

        double discountPercentage;
            // Adjust based on selection
            discountPercentage = switch (selectedDiscount) {
                case "0%"  -> 0.0;
                case "30%" -> 30.0;
                case "50%" -> 50.0;
                case "70%" -> 70.0;
                default -> 0.0;
            };
        // Set the discount for the current order
        currentOrder.setDiscount(discountPercentage);
    }//GEN-LAST:event_cbDiscountActionPerformed

    private void addIAmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIAmericanoActionPerformed
        addToCart("D07", "Iced Americano", qtyIAmericano);
    }//GEN-LAST:event_addIAmericanoActionPerformed

    private void addIGreenTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIGreenTeaActionPerformed
        addToCart("D08", "Iced Green Tea", qtyIGreenTea);
    }//GEN-LAST:event_addIGreenTeaActionPerformed

    private void addHGreenTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHGreenTeaActionPerformed
        addToCart("D04", "Hot Green Tea", qtyHGreenTea);
    }//GEN-LAST:event_addHGreenTeaActionPerformed

    private void addHCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHCappuccinoActionPerformed
        addToCart("D03", "Hot Cappuccino", qtyHCappuccino);
    }//GEN-LAST:event_addHCappuccinoActionPerformed

    private void addHLatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHLatteActionPerformed
        addToCart("D01", "Hot Latte", qtyHLatte);
    }//GEN-LAST:event_addHLatteActionPerformed

    private void addHEspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHEspressoActionPerformed
        addToCart("D02", "Hot Espresso", qtyHEspresso);
    }//GEN-LAST:event_addHEspressoActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btExitActionPerformed

    // Updated addToCart - Now it finds the price itself!
    private void addToCart(String pid, String name, javax.swing.JSpinner qtySpinner) {
        // 1. Get Quantity
        int quantity = (Integer) qtySpinner.getValue();

        if (quantity <= 0) {
            JOptionPane.showMessageDialog(this, "Please select a quantity > 0", "Invalid", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. FETCH PRICE FROM DATABASE (The Dynamic Link)
        double currentPrice = getPriceFromDB(pid); 

        // Safety check: If price is 0, maybe ID is wrong or DB is empty
        if (currentPrice == 0.0) {
            JOptionPane.showMessageDialog(this, "Error: Product ID " + pid + " not found in database or price is 0!");
            return;
        }

        // 3. Open Customization Dialog using the DB Price
        DrinkCustomizationDialog dialog = new DrinkCustomizationDialog(this, name, currentPrice);
        dialog.setVisible(true);

        // 4. If User Confirms...
        if (dialog.isConfirmed()) {
            Product product = new Product(
                pid,
                name,
                currentPrice, // Uses the price from DB
                quantity,
                dialog.getDrinkSize(),
                dialog.getSugarLevel(),
                dialog.getIceLevel(),
                dialog.hasExtraShot()
            );

            currentOrder.addProduct(product);

            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.addRow(new Object[] {
                product.getName(),
                String.format("$%.2f", product.getUnitFinalPrice()), 
                quantity,
                product.getCustomizationDetails(),
                String.format("$%.2f", product.getTotal())
            });

            qtySpinner.setValue(0);
        }
    }
    
    private void saveOrderToDatabase(double finalTotal) {
        try {
            // ---------------------------------------------------
            // STEP 1: SAVE THE MAIN RECEIPT (Who paid & How much)
            // ---------------------------------------------------
            String sqlOrder = "INSERT INTO orders (total_price, order_date) VALUES (?, NOW())";

            // We use RETURN_GENERATED_KEYS so SQL tells us the new Order ID (e.g., #105)
            pst = con.prepareStatement(sqlOrder, java.sql.Statement.RETURN_GENERATED_KEYS);
            pst.setDouble(1, finalTotal);
            pst.executeUpdate();

            // Get the Order ID that SQL just created
            rs = pst.getGeneratedKeys();
            int newOrderId = 0;
            if (rs.next()) {
                newOrderId = rs.getInt(1);
            }

            // ---------------------------------------------------
            // STEP 2: SAVE THE ITEMS (What they bought)
            // ---------------------------------------------------
            String sqlItem = "INSERT INTO order_items (order_id, product_pid, product_name, quantity, price, customization) VALUES (?, ?, ?, ?, ?, ?)";
            pst = con.prepareStatement(sqlItem);

            // Loop through the list of products in your Order object
            for (Product p : currentOrder.getProducts()) {
                pst.setInt(1, newOrderId);          // The Receipt # we just got
                pst.setString(2, p.getId());        // The Menu ID (e.g., D1)
                pst.setString(3, p.getName());      // The Name (e.g., Hot Latte)
                pst.setInt(4, p.getQuantity());     // The Qty
                pst.setDouble(5, p.getTotal());     // The Total Price for this line
                pst.setString(6, p.getCustomizationDetails()); // String like "Small, No Ice"

                pst.addBatch(); // Add to the queue (faster than saving one by one)
            }

            pst.executeBatch(); // Send the whole queue to the database

            // ---------------------------------------------------
            // STEP 3: SUCCESS & CLEANUP
            // ---------------------------------------------------
            JOptionPane.showMessageDialog(this, "Payment Successful!\nReceipt #" + newOrderId + " Saved.");

            // Clear the Order Logic
            currentOrder.clear(); 

            // Clear the GUI Table
            DefaultTableModel model = (DefaultTableModel) table.getModel();
            model.setRowCount(0); 

            // Reset Labels
            lbSubtotal.setText("");
            lbTotal.setText("");

        } catch (java.sql.SQLException e) {
            JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
            e.printStackTrace();
        } finally {
            // Good practice: Close connections to prevent memory leaks
            try {
                if (rs != null) rs.close();
                if (pst != null) pst.close();
                // Do not close 'con' if you use a shared static connection in db.java
            } catch (java.sql.SQLException ex) {
                ex.printStackTrace();
            }
        }
    }
    
    // Helper method to fetch the latest price from the database
    private double getPriceFromDB(String pid) {
        double price = 0.0;
        try {
            java.sql.Connection con = db.myCon();
            // Make sure your table name is 'product' and column is 'Price'
            String sql = "SELECT Price FROM Product WHERE PID = ?";

            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, pid);

            java.sql.ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                price = rs.getDouble("Price");
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error fetching price: " + e.getMessage());
        }
        return price;
    }
    
    private void btSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubtotalActionPerformed
        // 1. Ask the Order logic to sum up the products
        double sub = currentOrder.calculateSubtotal();

        // 2. Update the Subtotal text field
        lbSubtotal.setText(String.format("$%.2f", sub));
    }//GEN-LAST:event_btSubtotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cake;
    private javax.swing.JPanel Drink;
    private javax.swing.JButton addHCappuccino;
    private javax.swing.JButton addHEspresso;
    private javax.swing.JButton addHGreenTea;
    private javax.swing.JButton addHLatte;
    private javax.swing.JButton addIAmericano;
    private javax.swing.JButton addICappuccino;
    private javax.swing.JButton addIGreenTea;
    private javax.swing.JButton addILatte;
    private javax.swing.JPanel body;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btSubtotal;
    private javax.swing.JButton btTotal;
    private javax.swing.JPanel cContainer;
    private javax.swing.JComboBox<String> cbDiscount;
    private javax.swing.JPanel dContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbCake;
    private javax.swing.JLabel lbDrink;
    private javax.swing.JTextField lbSubtotal;
    private javax.swing.JTextField lbTotal;
    private javax.swing.JPanel pHCappuccino;
    private javax.swing.JPanel pHEspresso;
    private javax.swing.JPanel pHGreenTea;
    private javax.swing.JPanel pHLatte;
    private javax.swing.JPanel pIAmericano;
    private javax.swing.JPanel pICappuccino;
    private javax.swing.JPanel pIGreenTea;
    private javax.swing.JPanel pILatte;
    private javax.swing.JSpinner qtyHCappuccino;
    private javax.swing.JSpinner qtyHEspresso;
    private javax.swing.JSpinner qtyHGreenTea;
    private javax.swing.JSpinner qtyHLatte;
    private javax.swing.JSpinner qtyIAmericano;
    private javax.swing.JSpinner qtyICappuccino;
    private javax.swing.JSpinner qtyIGreenTea;
    private javax.swing.JSpinner qtyILatte;
    private javax.swing.JPanel right;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
