package OOP;

import Controllers.Controller;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GUI extends javax.swing.JFrame {

    private Order currentOrder = new Order();
    private Controller controller;
    
    java.sql.Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    public GUI() {
        initComponents(); 
        
        controller = new Controller(this, currentOrder);
        con = db.myCon();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        btExit = new javax.swing.JButton();
        lbCake = new javax.swing.JLabel();
        lbDrink = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbAdmin = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        Drink = new javax.swing.JPanel();
        dP1 = new javax.swing.JPanel();
        btNext = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        pIChocolate1 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        addIChocolate1 = new javax.swing.JButton();
        qtyIChocolate1 = new javax.swing.JSpinner();
        pIGreenTea1 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        addIGreenTea1 = new javax.swing.JButton();
        qtyIGreenTea1 = new javax.swing.JSpinner();
        pICappuccino1 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        addICappuccino1 = new javax.swing.JButton();
        qtyICappuccino1 = new javax.swing.JSpinner();
        pILatte1 = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        addILatte1 = new javax.swing.JButton();
        qtyILatte1 = new javax.swing.JSpinner();
        pIAmericano1 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        addIAmericano1 = new javax.swing.JButton();
        qtyIAmericano1 = new javax.swing.JSpinner();
        pHLatte1 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        addHLatte1 = new javax.swing.JButton();
        qtyHLatte1 = new javax.swing.JSpinner();
        pHCappuccino1 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        addHCappuccino1 = new javax.swing.JButton();
        qtyHCappuccino1 = new javax.swing.JSpinner();
        pHGreenTea1 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        addHGreenTea1 = new javax.swing.JButton();
        qtyHGreenTea1 = new javax.swing.JSpinner();
        pHEspresso1 = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        addHEspresso1 = new javax.swing.JButton();
        qtyHEspresso1 = new javax.swing.JSpinner();
        dP2 = new javax.swing.JPanel();
        btBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pHLatte = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        addHLatte = new javax.swing.JButton();
        qtyHLatte = new javax.swing.JSpinner();
        pHCappuccino = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        addHCappuccino = new javax.swing.JButton();
        qtyHCappuccino = new javax.swing.JSpinner();
        pHGreenTea = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        addHGreenTea = new javax.swing.JButton();
        qtyHGreenTea = new javax.swing.JSpinner();
        pHEspresso = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        addHEspresso = new javax.swing.JButton();
        qtyHEspresso = new javax.swing.JSpinner();
        Cake = new javax.swing.JPanel();
        cP1 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        pIChocolate2 = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        addIChocolate2 = new javax.swing.JButton();
        qtyIChocolate2 = new javax.swing.JSpinner();
        pIGreenTea2 = new javax.swing.JPanel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        addIGreenTea2 = new javax.swing.JButton();
        qtyIGreenTea2 = new javax.swing.JSpinner();
        pICappuccino2 = new javax.swing.JPanel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        addICappuccino2 = new javax.swing.JButton();
        qtyICappuccino2 = new javax.swing.JSpinner();
        pILatte2 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        addILatte2 = new javax.swing.JButton();
        qtyILatte2 = new javax.swing.JSpinner();
        pIAmericano2 = new javax.swing.JPanel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        addIAmericano2 = new javax.swing.JButton();
        qtyIAmericano2 = new javax.swing.JSpinner();
        pHLatte2 = new javax.swing.JPanel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        addHLatte2 = new javax.swing.JButton();
        qtyHLatte2 = new javax.swing.JSpinner();
        pHCappuccino2 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        addHCappuccino2 = new javax.swing.JButton();
        qtyHCappuccino2 = new javax.swing.JSpinner();
        pHGreenTea2 = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        addHGreenTea2 = new javax.swing.JButton();
        qtyHGreenTea2 = new javax.swing.JSpinner();
        pHEspresso2 = new javax.swing.JPanel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        addHEspresso2 = new javax.swing.JButton();
        qtyHEspresso2 = new javax.swing.JSpinner();
        right = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbSubtotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbDiscount = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JTextField();
        btTotal = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btSubtotal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1512, 982));
        getContentPane().setLayout(null);

        sidePanel.setBackground(new java.awt.Color(255, 255, 255));
        sidePanel.setLayout(null);

        btExit.setText("Exit");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        sidePanel.add(btExit);
        btExit.setBounds(40, 800, 72, 40);

        lbCake.setBackground(new java.awt.Color(255, 255, 255));
        lbCake.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        lbCake.setForeground(new java.awt.Color(51, 51, 51));
        lbCake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCake.setText("Cake");
        lbCake.setToolTipText("");
        lbCake.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbCake.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbCake.setOpaque(true);
        lbCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCakeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCakeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCakeMouseExited(evt);
            }
        });
        sidePanel.add(lbCake);
        lbCake.setBounds(0, 260, 160, 70);

        lbDrink.setBackground(new java.awt.Color(255, 255, 255));
        lbDrink.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        lbDrink.setForeground(new java.awt.Color(51, 51, 51));
        lbDrink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDrink.setText("Drink ");
        lbDrink.setToolTipText("");
        lbDrink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbDrink.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbDrink.setOpaque(true);
        lbDrink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDrinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbDrinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbDrinkMouseExited(evt);
            }
        });
        sidePanel.add(lbDrink);
        lbDrink.setBounds(0, 180, 160, 70);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/image 10.png"))); // NOI18N
        sidePanel.add(jLabel6);
        jLabel6.setBounds(20, 30, 120, 120);

        lbAdmin.setBackground(new java.awt.Color(255, 255, 255));
        lbAdmin.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 12)); // NOI18N
        lbAdmin.setForeground(new java.awt.Color(51, 51, 51));
        lbAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAdmin.setText("Admin");
        lbAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbAdmin.setOpaque(true);
        lbAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAdminMouseClicked(evt);
            }
        });
        sidePanel.add(lbAdmin);
        lbAdmin.setBounds(0, 750, 160, 40);

        getContentPane().add(sidePanel);
        sidePanel.setBounds(0, 0, 160, 980);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new java.awt.CardLayout());

        Drink.setLayout(new java.awt.CardLayout());

        dP1.setBackground(new java.awt.Color(245, 245, 245));
        dP1.setLayout(null);

        btNext.setText("Next");
        btNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNextActionPerformed(evt);
            }
        });
        dP1.add(btNext);
        btNext.setBounds(610, 50, 78, 30);

        jLabel31.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jLabel31.setText("Drink");
        dP1.add(jLabel31);
        jLabel31.setBounds(30, 30, 70, 50);

        pIChocolate1.setBackground(new java.awt.Color(255, 255, 255));
        pIChocolate1.setLayout(null);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/image 5.png"))); // NOI18N
        pIChocolate1.add(jLabel37);
        jLabel37.setBounds(20, -10, 150, 150);

        jLabel38.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel38.setText("1.5$");
        pIChocolate1.add(jLabel38);
        jLabel38.setBounds(10, 180, 40, 16);

        jLabel39.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel39.setText("Iced Chocolate");
        pIChocolate1.add(jLabel39);
        jLabel39.setBounds(10, 160, 120, 16);

        addIChocolate1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addIChocolate1.setText("ADD");
        addIChocolate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIChocolate1ActionPerformed(evt);
            }
        });
        pIChocolate1.add(addIChocolate1);
        addIChocolate1.setBounds(130, 160, 60, 60);

        qtyIChocolate1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pIChocolate1.add(qtyIChocolate1);
        qtyIChocolate1.setBounds(10, 200, 64, 20);

        dP1.add(pIChocolate1);
        pIChocolate1.setBounds(490, 610, 200, 240);

        pIGreenTea1.setBackground(new java.awt.Color(255, 255, 255));
        pIGreenTea1.setLayout(null);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/image 2.png"))); // NOI18N
        pIGreenTea1.add(jLabel32);
        jLabel32.setBounds(20, 0, 150, 150);

        jLabel33.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel33.setText("1.5$");
        pIGreenTea1.add(jLabel33);
        jLabel33.setBounds(10, 180, 40, 16);

        jLabel40.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel40.setText("Iced Green Tea");
        pIGreenTea1.add(jLabel40);
        jLabel40.setBounds(10, 160, 120, 16);

        addIGreenTea1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addIGreenTea1.setText("ADD");
        addIGreenTea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIGreenTea1ActionPerformed(evt);
            }
        });
        pIGreenTea1.add(addIGreenTea1);
        addIGreenTea1.setBounds(130, 160, 60, 60);

        qtyIGreenTea1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pIGreenTea1.add(qtyIGreenTea1);
        qtyIGreenTea1.setBounds(10, 200, 64, 20);

        dP1.add(pIGreenTea1);
        pIGreenTea1.setBounds(260, 610, 200, 240);

        pICappuccino1.setBackground(new java.awt.Color(255, 255, 255));
        pICappuccino1.setLayout(null);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/image 4.png"))); // NOI18N
        pICappuccino1.add(jLabel41);
        jLabel41.setBounds(20, 0, 150, 150);

        jLabel42.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel42.setText("2.0$");
        pICappuccino1.add(jLabel42);
        jLabel42.setBounds(10, 180, 40, 16);

        jLabel43.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel43.setText("Iced Cappuccino");
        pICappuccino1.add(jLabel43);
        jLabel43.setBounds(10, 160, 120, 16);

        addICappuccino1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addICappuccino1.setText("ADD");
        addICappuccino1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addICappuccino1ActionPerformed(evt);
            }
        });
        pICappuccino1.add(addICappuccino1);
        addICappuccino1.setBounds(130, 160, 60, 60);

        qtyICappuccino1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pICappuccino1.add(qtyICappuccino1);
        qtyICappuccino1.setBounds(10, 200, 64, 20);

        dP1.add(pICappuccino1);
        pICappuccino1.setBounds(30, 610, 200, 240);

        pILatte1.setBackground(new java.awt.Color(255, 255, 255));
        pILatte1.setLayout(null);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/image 1.png"))); // NOI18N
        pILatte1.add(jLabel44);
        jLabel44.setBounds(20, 0, 150, 150);

        jLabel45.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel45.setText("2.0$");
        pILatte1.add(jLabel45);
        jLabel45.setBounds(10, 180, 40, 16);

        jLabel46.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel46.setText("Iced Latte");
        pILatte1.add(jLabel46);
        jLabel46.setBounds(10, 160, 80, 16);

        addILatte1.setText("ADD");
        addILatte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addILatte1ActionPerformed(evt);
            }
        });
        pILatte1.add(addILatte1);
        addILatte1.setBounds(130, 160, 60, 60);

        qtyILatte1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pILatte1.add(qtyILatte1);
        qtyILatte1.setBounds(10, 200, 64, 20);

        dP1.add(pILatte1);
        pILatte1.setBounds(260, 350, 200, 240);

        pIAmericano1.setBackground(new java.awt.Color(255, 255, 255));
        pIAmericano1.setLayout(null);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/image 3.png"))); // NOI18N
        pIAmericano1.add(jLabel47);
        jLabel47.setBounds(20, 0, 150, 150);

        jLabel48.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel48.setText("1.5$");
        pIAmericano1.add(jLabel48);
        jLabel48.setBounds(10, 180, 40, 16);

        jLabel49.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel49.setText("Iced Americano");
        pIAmericano1.add(jLabel49);
        jLabel49.setBounds(10, 160, 110, 16);

        addIAmericano1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addIAmericano1.setText("ADD");
        addIAmericano1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIAmericano1ActionPerformed(evt);
            }
        });
        pIAmericano1.add(addIAmericano1);
        addIAmericano1.setBounds(130, 160, 60, 60);

        qtyIAmericano1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pIAmericano1.add(qtyIAmericano1);
        qtyIAmericano1.setBounds(10, 200, 64, 20);

        dP1.add(pIAmericano1);
        pIAmericano1.setBounds(490, 350, 200, 240);

        pHLatte1.setBackground(new java.awt.Color(255, 255, 255));
        pHLatte1.setLayout(null);

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/98d03bd7c2a93f2e4f9972efa9da61be.png"))); // NOI18N
        pHLatte1.add(jLabel50);
        jLabel50.setBounds(20, 0, 150, 150);

        jLabel51.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel51.setText("1,5$");
        pHLatte1.add(jLabel51);
        jLabel51.setBounds(10, 180, 40, 16);

        jLabel52.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel52.setText("Hot Latte");
        pHLatte1.add(jLabel52);
        jLabel52.setBounds(10, 160, 80, 16);

        addHLatte1.setText("ADD");
        addHLatte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHLatte1ActionPerformed(evt);
            }
        });
        pHLatte1.add(addHLatte1);
        addHLatte1.setBounds(130, 160, 60, 60);

        qtyHLatte1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pHLatte1.add(qtyHLatte1);
        qtyHLatte1.setBounds(10, 200, 64, 20);

        dP1.add(pHLatte1);
        pHLatte1.setBounds(30, 90, 200, 240);

        pHCappuccino1.setBackground(new java.awt.Color(255, 255, 255));
        pHCappuccino1.setLayout(null);

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/46e2af89e9d690dd555be8a7e486bb96.png"))); // NOI18N
        pHCappuccino1.add(jLabel53);
        jLabel53.setBounds(20, 0, 150, 150);

        jLabel54.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel54.setText("1.5$");
        pHCappuccino1.add(jLabel54);
        jLabel54.setBounds(10, 180, 40, 16);

        jLabel55.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel55.setText("Hot Cappuccino");
        pHCappuccino1.add(jLabel55);
        jLabel55.setBounds(10, 160, 120, 16);

        addHCappuccino1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addHCappuccino1.setText("ADD");
        addHCappuccino1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHCappuccino1ActionPerformed(evt);
            }
        });
        pHCappuccino1.add(addHCappuccino1);
        addHCappuccino1.setBounds(130, 160, 60, 60);

        qtyHCappuccino1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pHCappuccino1.add(qtyHCappuccino1);
        qtyHCappuccino1.setBounds(10, 200, 64, 20);

        dP1.add(pHCappuccino1);
        pHCappuccino1.setBounds(490, 90, 200, 240);

        pHGreenTea1.setBackground(new java.awt.Color(255, 255, 255));
        pHGreenTea1.setLayout(null);

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/73745cbf117bac2f7bd80a018767976b.png"))); // NOI18N
        pHGreenTea1.add(jLabel56);
        jLabel56.setBounds(20, 0, 150, 150);

        jLabel57.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel57.setText("1.5$");
        pHGreenTea1.add(jLabel57);
        jLabel57.setBounds(10, 180, 40, 16);

        jLabel58.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel58.setText("Hot Green Tea");
        pHGreenTea1.add(jLabel58);
        jLabel58.setBounds(10, 160, 120, 16);

        addHGreenTea1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addHGreenTea1.setText("ADD");
        addHGreenTea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHGreenTea1ActionPerformed(evt);
            }
        });
        pHGreenTea1.add(addHGreenTea1);
        addHGreenTea1.setBounds(130, 160, 60, 60);

        qtyHGreenTea1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pHGreenTea1.add(qtyHGreenTea1);
        qtyHGreenTea1.setBounds(10, 200, 64, 20);

        dP1.add(pHGreenTea1);
        pHGreenTea1.setBounds(30, 350, 200, 240);

        pHEspresso1.setBackground(new java.awt.Color(255, 255, 255));
        pHEspresso1.setLayout(null);

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/d6600f2db33c4ccad883a646531c8b23.png"))); // NOI18N
        pHEspresso1.add(jLabel59);
        jLabel59.setBounds(20, 0, 150, 150);

        jLabel60.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel60.setText("1.0$");
        pHEspresso1.add(jLabel60);
        jLabel60.setBounds(10, 180, 40, 16);

        jLabel61.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel61.setText("Hot Espresso");
        pHEspresso1.add(jLabel61);
        jLabel61.setBounds(10, 160, 110, 16);

        addHEspresso1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addHEspresso1.setText("ADD");
        addHEspresso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHEspresso1ActionPerformed(evt);
            }
        });
        pHEspresso1.add(addHEspresso1);
        addHEspresso1.setBounds(130, 160, 60, 60);

        qtyHEspresso1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pHEspresso1.add(qtyHEspresso1);
        qtyHEspresso1.setBounds(10, 200, 64, 20);

        dP1.add(pHEspresso1);
        pHEspresso1.setBounds(260, 90, 200, 240);

        Drink.add(dP1, "card2");

        dP2.setBackground(new java.awt.Color(245, 245, 245));
        dP2.setLayout(null);

        btBack.setText("Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });
        dP2.add(btBack);
        btBack.setBounds(610, 50, 78, 30);

        jLabel1.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jLabel1.setText("Drink");
        dP2.add(jLabel1);
        jLabel1.setBounds(30, 30, 70, 50);

        pHLatte.setBackground(new java.awt.Color(255, 255, 255));
        pHLatte.setLayout(null);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/image 7.png"))); // NOI18N
        pHLatte.add(jLabel25);
        jLabel25.setBounds(20, 0, 150, 150);

        jLabel26.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel26.setText("2,5$");
        pHLatte.add(jLabel26);
        jLabel26.setBounds(10, 180, 40, 16);

        jLabel27.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel27.setText("Green Tea Frappe");
        pHLatte.add(jLabel27);
        jLabel27.setBounds(10, 160, 120, 16);

        addHLatte.setText("ADD");
        addHLatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHLatteActionPerformed(evt);
            }
        });
        pHLatte.add(addHLatte);
        addHLatte.setBounds(130, 160, 60, 60);

        qtyHLatte.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pHLatte.add(qtyHLatte);
        qtyHLatte.setBounds(10, 200, 64, 20);

        dP2.add(pHLatte);
        pHLatte.setBounds(30, 90, 200, 240);

        pHCappuccino.setBackground(new java.awt.Color(255, 255, 255));
        pHCappuccino.setLayout(null);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/image 12.png"))); // NOI18N
        pHCappuccino.add(jLabel22);
        jLabel22.setBounds(20, 0, 150, 150);

        jLabel23.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel23.setText("2.5$");
        pHCappuccino.add(jLabel23);
        jLabel23.setBounds(10, 180, 40, 16);

        jLabel24.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 12)); // NOI18N
        jLabel24.setText("Frappe Cappuccino");
        pHCappuccino.add(jLabel24);
        jLabel24.setBounds(10, 160, 130, 15);

        addHCappuccino.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addHCappuccino.setText("ADD");
        addHCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHCappuccinoActionPerformed(evt);
            }
        });
        pHCappuccino.add(addHCappuccino);
        addHCappuccino.setBounds(130, 160, 60, 60);

        qtyHCappuccino.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pHCappuccino.add(qtyHCappuccino);
        qtyHCappuccino.setBounds(10, 200, 64, 20);

        dP2.add(pHCappuccino);
        pHCappuccino.setBounds(490, 90, 200, 240);

        pHGreenTea.setBackground(new java.awt.Color(255, 255, 255));
        pHGreenTea.setLayout(null);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/image 8.png"))); // NOI18N
        pHGreenTea.add(jLabel19);
        jLabel19.setBounds(20, 0, 150, 150);

        jLabel20.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel20.setText("3$");
        pHGreenTea.add(jLabel20);
        jLabel20.setBounds(10, 180, 40, 16);

        jLabel21.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel21.setText("Berry Smoothie");
        pHGreenTea.add(jLabel21);
        jLabel21.setBounds(10, 160, 120, 16);

        addHGreenTea.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addHGreenTea.setText("ADD");
        addHGreenTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHGreenTeaActionPerformed(evt);
            }
        });
        pHGreenTea.add(addHGreenTea);
        addHGreenTea.setBounds(130, 160, 60, 60);

        qtyHGreenTea.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pHGreenTea.add(qtyHGreenTea);
        qtyHGreenTea.setBounds(10, 200, 64, 20);

        dP2.add(pHGreenTea);
        pHGreenTea.setBounds(30, 350, 200, 240);

        pHEspresso.setBackground(new java.awt.Color(255, 255, 255));
        pHEspresso.setLayout(null);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/image 6.png"))); // NOI18N
        pHEspresso.add(jLabel28);
        jLabel28.setBounds(20, 0, 150, 150);

        jLabel29.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel29.setText("2.5$");
        pHEspresso.add(jLabel29);
        jLabel29.setBounds(10, 180, 40, 16);

        jLabel30.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel30.setText("Chocolate Frappe");
        pHEspresso.add(jLabel30);
        jLabel30.setBounds(10, 160, 120, 16);

        addHEspresso.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addHEspresso.setText("ADD");
        addHEspresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHEspressoActionPerformed(evt);
            }
        });
        pHEspresso.add(addHEspresso);
        addHEspresso.setBounds(130, 160, 60, 60);

        qtyHEspresso.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pHEspresso.add(qtyHEspresso);
        qtyHEspresso.setBounds(10, 200, 64, 20);

        dP2.add(pHEspresso);
        pHEspresso.setBounds(260, 90, 200, 240);

        Drink.add(dP2, "card2");

        body.add(Drink, "card2");

        Cake.setLayout(new java.awt.CardLayout());

        cP1.setBackground(new java.awt.Color(245, 245, 245));
        cP1.setLayout(null);

        jLabel62.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jLabel62.setText("Cake");
        cP1.add(jLabel62);
        jLabel62.setBounds(30, 30, 70, 50);

        pIChocolate2.setBackground(new java.awt.Color(255, 255, 255));
        pIChocolate2.setLayout(null);

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/image 5.png"))); // NOI18N
        pIChocolate2.add(jLabel63);
        jLabel63.setBounds(20, -10, 150, 150);

        jLabel64.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel64.setText("1.5$");
        pIChocolate2.add(jLabel64);
        jLabel64.setBounds(10, 180, 40, 16);

        jLabel65.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel65.setText("Iced Chocolate");
        pIChocolate2.add(jLabel65);
        jLabel65.setBounds(10, 160, 120, 16);

        addIChocolate2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addIChocolate2.setText("ADD");
        addIChocolate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIChocolate2ActionPerformed(evt);
            }
        });
        pIChocolate2.add(addIChocolate2);
        addIChocolate2.setBounds(130, 160, 60, 60);

        qtyIChocolate2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pIChocolate2.add(qtyIChocolate2);
        qtyIChocolate2.setBounds(10, 200, 64, 20);

        cP1.add(pIChocolate2);
        pIChocolate2.setBounds(490, 610, 200, 240);

        pIGreenTea2.setBackground(new java.awt.Color(255, 255, 255));
        pIGreenTea2.setLayout(null);

        jLabel66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/image 2.png"))); // NOI18N
        pIGreenTea2.add(jLabel66);
        jLabel66.setBounds(20, 0, 150, 150);

        jLabel67.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel67.setText("1.5$");
        pIGreenTea2.add(jLabel67);
        jLabel67.setBounds(10, 180, 40, 16);

        jLabel68.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel68.setText("Iced Green Tea");
        pIGreenTea2.add(jLabel68);
        jLabel68.setBounds(10, 160, 120, 16);

        addIGreenTea2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addIGreenTea2.setText("ADD");
        addIGreenTea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIGreenTea2ActionPerformed(evt);
            }
        });
        pIGreenTea2.add(addIGreenTea2);
        addIGreenTea2.setBounds(130, 160, 60, 60);

        qtyIGreenTea2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pIGreenTea2.add(qtyIGreenTea2);
        qtyIGreenTea2.setBounds(10, 200, 64, 20);

        cP1.add(pIGreenTea2);
        pIGreenTea2.setBounds(260, 610, 200, 240);

        pICappuccino2.setBackground(new java.awt.Color(255, 255, 255));
        pICappuccino2.setLayout(null);

        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/image 4.png"))); // NOI18N
        pICappuccino2.add(jLabel69);
        jLabel69.setBounds(20, 0, 150, 150);

        jLabel70.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel70.setText("2.0$");
        pICappuccino2.add(jLabel70);
        jLabel70.setBounds(10, 180, 40, 16);

        jLabel71.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel71.setText("Iced Cappuccino");
        pICappuccino2.add(jLabel71);
        jLabel71.setBounds(10, 160, 120, 16);

        addICappuccino2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addICappuccino2.setText("ADD");
        addICappuccino2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addICappuccino2ActionPerformed(evt);
            }
        });
        pICappuccino2.add(addICappuccino2);
        addICappuccino2.setBounds(130, 160, 60, 60);

        qtyICappuccino2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pICappuccino2.add(qtyICappuccino2);
        qtyICappuccino2.setBounds(10, 200, 64, 20);

        cP1.add(pICappuccino2);
        pICappuccino2.setBounds(30, 610, 200, 240);

        pILatte2.setBackground(new java.awt.Color(255, 255, 255));
        pILatte2.setLayout(null);

        jLabel72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/image 1.png"))); // NOI18N
        pILatte2.add(jLabel72);
        jLabel72.setBounds(20, 0, 150, 150);

        jLabel73.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel73.setText("2.0$");
        pILatte2.add(jLabel73);
        jLabel73.setBounds(10, 180, 40, 16);

        jLabel74.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel74.setText("Iced Latte");
        pILatte2.add(jLabel74);
        jLabel74.setBounds(10, 160, 80, 16);

        addILatte2.setText("ADD");
        addILatte2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addILatte2ActionPerformed(evt);
            }
        });
        pILatte2.add(addILatte2);
        addILatte2.setBounds(130, 160, 60, 60);

        qtyILatte2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pILatte2.add(qtyILatte2);
        qtyILatte2.setBounds(10, 200, 64, 20);

        cP1.add(pILatte2);
        pILatte2.setBounds(260, 350, 200, 240);

        pIAmericano2.setBackground(new java.awt.Color(255, 255, 255));
        pIAmericano2.setLayout(null);

        jLabel75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/image 3.png"))); // NOI18N
        pIAmericano2.add(jLabel75);
        jLabel75.setBounds(20, 0, 150, 150);

        jLabel76.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel76.setText("1.5$");
        pIAmericano2.add(jLabel76);
        jLabel76.setBounds(10, 180, 40, 16);

        jLabel77.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel77.setText("Iced Americano");
        pIAmericano2.add(jLabel77);
        jLabel77.setBounds(10, 160, 110, 16);

        addIAmericano2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addIAmericano2.setText("ADD");
        addIAmericano2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIAmericano2ActionPerformed(evt);
            }
        });
        pIAmericano2.add(addIAmericano2);
        addIAmericano2.setBounds(130, 160, 60, 60);

        qtyIAmericano2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pIAmericano2.add(qtyIAmericano2);
        qtyIAmericano2.setBounds(10, 200, 64, 20);

        cP1.add(pIAmericano2);
        pIAmericano2.setBounds(490, 350, 200, 240);

        pHLatte2.setBackground(new java.awt.Color(255, 255, 255));
        pHLatte2.setLayout(null);

        jLabel78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/98d03bd7c2a93f2e4f9972efa9da61be.png"))); // NOI18N
        pHLatte2.add(jLabel78);
        jLabel78.setBounds(20, 0, 150, 150);

        jLabel79.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel79.setText("1,5$");
        pHLatte2.add(jLabel79);
        jLabel79.setBounds(10, 180, 40, 16);

        jLabel80.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel80.setText("Hot Latte");
        pHLatte2.add(jLabel80);
        jLabel80.setBounds(10, 160, 80, 16);

        addHLatte2.setText("ADD");
        addHLatte2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHLatte2ActionPerformed(evt);
            }
        });
        pHLatte2.add(addHLatte2);
        addHLatte2.setBounds(130, 160, 60, 60);

        qtyHLatte2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pHLatte2.add(qtyHLatte2);
        qtyHLatte2.setBounds(10, 200, 64, 20);

        cP1.add(pHLatte2);
        pHLatte2.setBounds(30, 90, 200, 240);

        pHCappuccino2.setBackground(new java.awt.Color(255, 255, 255));
        pHCappuccino2.setLayout(null);

        jLabel81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/46e2af89e9d690dd555be8a7e486bb96.png"))); // NOI18N
        pHCappuccino2.add(jLabel81);
        jLabel81.setBounds(20, 0, 150, 150);

        jLabel82.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel82.setText("1.5$");
        pHCappuccino2.add(jLabel82);
        jLabel82.setBounds(10, 180, 40, 16);

        jLabel83.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel83.setText("Hot Cappuccino");
        pHCappuccino2.add(jLabel83);
        jLabel83.setBounds(10, 160, 120, 16);

        addHCappuccino2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addHCappuccino2.setText("ADD");
        addHCappuccino2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHCappuccino2ActionPerformed(evt);
            }
        });
        pHCappuccino2.add(addHCappuccino2);
        addHCappuccino2.setBounds(130, 160, 60, 60);

        qtyHCappuccino2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pHCappuccino2.add(qtyHCappuccino2);
        qtyHCappuccino2.setBounds(10, 200, 64, 20);

        cP1.add(pHCappuccino2);
        pHCappuccino2.setBounds(490, 90, 200, 240);

        pHGreenTea2.setBackground(new java.awt.Color(255, 255, 255));
        pHGreenTea2.setLayout(null);

        jLabel84.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/73745cbf117bac2f7bd80a018767976b.png"))); // NOI18N
        pHGreenTea2.add(jLabel84);
        jLabel84.setBounds(20, 0, 150, 150);

        jLabel85.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel85.setText("1.5$");
        pHGreenTea2.add(jLabel85);
        jLabel85.setBounds(10, 180, 40, 16);

        jLabel86.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel86.setText("Hot Green Tea");
        pHGreenTea2.add(jLabel86);
        jLabel86.setBounds(10, 160, 120, 16);

        addHGreenTea2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addHGreenTea2.setText("ADD");
        addHGreenTea2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHGreenTea2ActionPerformed(evt);
            }
        });
        pHGreenTea2.add(addHGreenTea2);
        addHGreenTea2.setBounds(130, 160, 60, 60);

        qtyHGreenTea2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pHGreenTea2.add(qtyHGreenTea2);
        qtyHGreenTea2.setBounds(10, 200, 64, 20);

        cP1.add(pHGreenTea2);
        pHGreenTea2.setBounds(30, 350, 200, 240);

        pHEspresso2.setBackground(new java.awt.Color(255, 255, 255));
        pHEspresso2.setLayout(null);

        jLabel87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/d6600f2db33c4ccad883a646531c8b23.png"))); // NOI18N
        pHEspresso2.add(jLabel87);
        jLabel87.setBounds(20, 0, 150, 150);

        jLabel88.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel88.setText("1.0$");
        pHEspresso2.add(jLabel88);
        jLabel88.setBounds(10, 180, 40, 16);

        jLabel89.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel89.setText("Hot Espresso");
        pHEspresso2.add(jLabel89);
        jLabel89.setBounds(10, 160, 110, 16);

        addHEspresso2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addHEspresso2.setText("ADD");
        addHEspresso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHEspresso2ActionPerformed(evt);
            }
        });
        pHEspresso2.add(addHEspresso2);
        addHEspresso2.setBounds(130, 160, 60, 60);

        qtyHEspresso2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pHEspresso2.add(qtyHEspresso2);
        qtyHEspresso2.setBounds(10, 200, 64, 20);

        cP1.add(pHEspresso2);
        pHEspresso2.setBounds(260, 90, 200, 240);

        Cake.add(cP1, "card2");

        body.add(Cake, "card2");

        getContentPane().add(body);
        body.setBounds(160, 0, 750, 980);

        right.setBackground(new java.awt.Color(255, 255, 255));
        right.setLayout(null);

        table.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Price", "Qty", "Customization", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table);

        right.add(jScrollPane2);
        jScrollPane2.setBounds(10, 20, 580, 390);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(null);

        jLabel3.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        jLabel3.setText("Discount: ");
        jPanel17.add(jLabel3);
        jLabel3.setBounds(20, 60, 130, 30);

        lbSubtotal.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        lbSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbSubtotalActionPerformed(evt);
            }
        });
        jPanel17.add(lbSubtotal);
        lbSubtotal.setBounds(160, 10, 190, 30);

        jLabel4.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        jLabel4.setText("Subtotal: ");
        jPanel17.add(jLabel4);
        jLabel4.setBounds(20, 10, 119, 30);

        cbDiscount.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        cbDiscount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "30%", "50%", "70%" }));
        cbDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDiscountActionPerformed(evt);
            }
        });
        jPanel17.add(cbDiscount);
        cbDiscount.setBounds(160, 60, 190, 30);

        jLabel5.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        jLabel5.setText("Total:");
        jPanel17.add(jLabel5);
        jLabel5.setBounds(20, 110, 59, 25);

        lbTotal.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        lbTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbTotalActionPerformed(evt);
            }
        });
        jPanel17.add(lbTotal);
        lbTotal.setBounds(160, 110, 190, 28);

        right.add(jPanel17);
        jPanel17.setBounds(20, 430, 370, 150);

        btTotal.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        btTotal.setText("Total");
        btTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTotalActionPerformed(evt);
            }
        });
        right.add(btTotal);
        btTotal.setBounds(190, 620, 130, 40);

        btDelete.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        right.add(btDelete);
        btDelete.setBounds(430, 440, 130, 30);

        btSubtotal.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        btSubtotal.setText("Subtotal");
        btSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubtotalActionPerformed(evt);
            }
        });
        right.add(btSubtotal);
        btSubtotal.setBounds(40, 620, 130, 40);

        getContentPane().add(right);
        right.setBounds(910, 0, 600, 980);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCakeMouseClicked
        body.removeAll();
        body.add(Cake);
        body.revalidate();
        body.repaint();
    }//GEN-LAST:event_lbCakeMouseClicked

    private void lbDrinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDrinkMouseClicked
        body.removeAll();
        body.add(Drink);
        body.revalidate();
        body.repaint();
    }//GEN-LAST:event_lbDrinkMouseClicked

    private void lbDrinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDrinkMouseExited
        lbDrink.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_lbDrinkMouseExited

    private void lbDrinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDrinkMouseEntered
        lbDrink.setBackground(new Color(229,214,192));
    }//GEN-LAST:event_lbDrinkMouseEntered

    private void lbCakeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCakeMouseEntered
        lbCake.setBackground(new Color(229,214,192));
    }//GEN-LAST:event_lbCakeMouseEntered

    private void lbCakeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCakeMouseExited
        lbCake.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_lbCakeMouseExited

    private void lbSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSubtotalActionPerformed

    private void lbTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbTotalActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int selectedRow = table.getSelectedRow();

        // 1. Check if the user actually clicked a row
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an item to delete.", "Delete Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Remove from the Logic (Order.java)
        // IMPORTANT: This must happen while the indexes still match!
        currentOrder.removeProduct(selectedRow);

        // 3. Remove from the View (JTable)
        model.removeRow(selectedRow);

        // Optional: Clear the Total label since the previous total is now wrong
        lbTotal.setText(""); 
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTotalActionPerformed
        // 1. Ask Order logic for the final price (it automatically applies the discount)
        double finalTotal = currentOrder.calculateTotal();

        // 2. Display it
        lbTotal.setText(String.format("$%.2f", finalTotal));

        // 3. Ask for Payment Confirmation
        int choice = JOptionPane.showConfirmDialog(this, 
                "Total Amount: " + String.format("$%.2f", finalTotal) + "\nProceed to payment?", 
                "Checkout", 
                JOptionPane.YES_NO_OPTION);

        // 4. If Yes, Save to Database
        if (choice == JOptionPane.YES_OPTION) {
            controller.saveOrderToDatabase(finalTotal);
        }
    }//GEN-LAST:event_btTotalActionPerformed

    private void cbDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDiscountActionPerformed
        // Get the selected discount percentage from the ComboBox
        String selectedDiscount = (String)cbDiscount.getSelectedItem();

        double discountPercentage;
            // Adjust based on selection
            discountPercentage = switch (selectedDiscount) {
                case "0%"  -> 0.0;
                case "30%" -> 30.0;
                case "50%" -> 50.0;
                case "70%" -> 70.0;
                default -> 0.0;
            };
        // Set the discount for the current order
        currentOrder.setDiscount(discountPercentage);
    }//GEN-LAST:event_cbDiscountActionPerformed

    private void addHGreenTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHGreenTeaActionPerformed
        controller.addToCart("D04", qtyHGreenTea);
    }//GEN-LAST:event_addHGreenTeaActionPerformed

    private void addHCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHCappuccinoActionPerformed
        controller.addToCart("D03", qtyHCappuccino);
    }//GEN-LAST:event_addHCappuccinoActionPerformed

    private void addHLatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHLatteActionPerformed
        controller.addToCart("D01", qtyHLatte);
    }//GEN-LAST:event_addHLatteActionPerformed

    private void addHEspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHEspressoActionPerformed
        controller.addToCart("D02", qtyHEspresso);
    }//GEN-LAST:event_addHEspressoActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btExitActionPerformed
 
    public javax.swing.JTable getTable() {
        return table;
    }

    public javax.swing.JTextField getLbTotal() {
        return lbTotal;
    }

    public javax.swing.JTextField getLbSubtotal() {
        return lbSubtotal;
    }
    
    private void btSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubtotalActionPerformed
        // 1. Ask the Order logic to sum up the products
        double sub = currentOrder.calculateSubtotal();

        // 2. Update the Subtotal text field
        lbSubtotal.setText(String.format("$%.2f", sub));
    }//GEN-LAST:event_btSubtotalActionPerformed

    private void lbAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAdminMouseClicked
        Admin​ ad = new Admin();
        ad.setVisible(true);
    }//GEN-LAST:event_lbAdminMouseClicked

    private void addHLatte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHLatte1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addHLatte1ActionPerformed

    private void addHCappuccino1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHCappuccino1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addHCappuccino1ActionPerformed

    private void addHGreenTea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHGreenTea1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addHGreenTea1ActionPerformed

    private void addHEspresso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHEspresso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addHEspresso1ActionPerformed

    private void btNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNextActionPerformed
        Drink.removeAll();
        Drink.add(dP2);
        Drink.revalidate();
        Drink.repaint();
    }//GEN-LAST:event_btNextActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        Drink.removeAll();
        Drink.add(dP1);
        Drink.revalidate();
        Drink.repaint(); 
    }//GEN-LAST:event_btBackActionPerformed

    private void addIAmericano1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIAmericano1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addIAmericano1ActionPerformed

    private void addILatte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addILatte1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addILatte1ActionPerformed

    private void addICappuccino1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addICappuccino1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addICappuccino1ActionPerformed

    private void addIGreenTea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIGreenTea1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addIGreenTea1ActionPerformed

    private void addIChocolate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIChocolate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addIChocolate1ActionPerformed

    private void addHEspresso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHEspresso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addHEspresso2ActionPerformed

    private void addHGreenTea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHGreenTea2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addHGreenTea2ActionPerformed

    private void addHCappuccino2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHCappuccino2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addHCappuccino2ActionPerformed

    private void addHLatte2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHLatte2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addHLatte2ActionPerformed

    private void addIAmericano2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIAmericano2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addIAmericano2ActionPerformed

    private void addILatte2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addILatte2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addILatte2ActionPerformed

    private void addICappuccino2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addICappuccino2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addICappuccino2ActionPerformed

    private void addIGreenTea2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIGreenTea2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addIGreenTea2ActionPerformed

    private void addIChocolate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIChocolate2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addIChocolate2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cake;
    private javax.swing.JPanel Drink;
    private javax.swing.JButton addHCappuccino;
    private javax.swing.JButton addHCappuccino1;
    private javax.swing.JButton addHCappuccino2;
    private javax.swing.JButton addHEspresso;
    private javax.swing.JButton addHEspresso1;
    private javax.swing.JButton addHEspresso2;
    private javax.swing.JButton addHGreenTea;
    private javax.swing.JButton addHGreenTea1;
    private javax.swing.JButton addHGreenTea2;
    private javax.swing.JButton addHLatte;
    private javax.swing.JButton addHLatte1;
    private javax.swing.JButton addHLatte2;
    private javax.swing.JButton addIAmericano1;
    private javax.swing.JButton addIAmericano2;
    private javax.swing.JButton addICappuccino1;
    private javax.swing.JButton addICappuccino2;
    private javax.swing.JButton addIChocolate1;
    private javax.swing.JButton addIChocolate2;
    private javax.swing.JButton addIGreenTea1;
    private javax.swing.JButton addIGreenTea2;
    private javax.swing.JButton addILatte1;
    private javax.swing.JButton addILatte2;
    private javax.swing.JPanel body;
    private javax.swing.JButton btBack;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btNext;
    private javax.swing.JButton btSubtotal;
    private javax.swing.JButton btTotal;
    private javax.swing.JPanel cP1;
    private javax.swing.JComboBox<String> cbDiscount;
    private javax.swing.JPanel dP1;
    private javax.swing.JPanel dP2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAdmin;
    private javax.swing.JLabel lbCake;
    private javax.swing.JLabel lbDrink;
    private javax.swing.JTextField lbSubtotal;
    private javax.swing.JTextField lbTotal;
    private javax.swing.JPanel pHCappuccino;
    private javax.swing.JPanel pHCappuccino1;
    private javax.swing.JPanel pHCappuccino2;
    private javax.swing.JPanel pHEspresso;
    private javax.swing.JPanel pHEspresso1;
    private javax.swing.JPanel pHEspresso2;
    private javax.swing.JPanel pHGreenTea;
    private javax.swing.JPanel pHGreenTea1;
    private javax.swing.JPanel pHGreenTea2;
    private javax.swing.JPanel pHLatte;
    private javax.swing.JPanel pHLatte1;
    private javax.swing.JPanel pHLatte2;
    private javax.swing.JPanel pIAmericano1;
    private javax.swing.JPanel pIAmericano2;
    private javax.swing.JPanel pICappuccino1;
    private javax.swing.JPanel pICappuccino2;
    private javax.swing.JPanel pIChocolate1;
    private javax.swing.JPanel pIChocolate2;
    private javax.swing.JPanel pIGreenTea1;
    private javax.swing.JPanel pIGreenTea2;
    private javax.swing.JPanel pILatte1;
    private javax.swing.JPanel pILatte2;
    private javax.swing.JSpinner qtyHCappuccino;
    private javax.swing.JSpinner qtyHCappuccino1;
    private javax.swing.JSpinner qtyHCappuccino2;
    private javax.swing.JSpinner qtyHEspresso;
    private javax.swing.JSpinner qtyHEspresso1;
    private javax.swing.JSpinner qtyHEspresso2;
    private javax.swing.JSpinner qtyHGreenTea;
    private javax.swing.JSpinner qtyHGreenTea1;
    private javax.swing.JSpinner qtyHGreenTea2;
    private javax.swing.JSpinner qtyHLatte;
    private javax.swing.JSpinner qtyHLatte1;
    private javax.swing.JSpinner qtyHLatte2;
    private javax.swing.JSpinner qtyIAmericano1;
    private javax.swing.JSpinner qtyIAmericano2;
    private javax.swing.JSpinner qtyICappuccino1;
    private javax.swing.JSpinner qtyICappuccino2;
    private javax.swing.JSpinner qtyIChocolate1;
    private javax.swing.JSpinner qtyIChocolate2;
    private javax.swing.JSpinner qtyIGreenTea1;
    private javax.swing.JSpinner qtyIGreenTea2;
    private javax.swing.JSpinner qtyILatte1;
    private javax.swing.JSpinner qtyILatte2;
    private javax.swing.JPanel right;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
