package Views;

import Controllers.Controller;
import Models.Order;
import Models.db;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GUI extends javax.swing.JFrame {

    private Order currentOrder = new Order();
    private Controller controller;
    
    java.sql.Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    public GUI() {
        initComponents(); 
        
        controller = new Controller(this, currentOrder);
        con = db.myCon();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        btExit = new javax.swing.JButton();
        lbCake = new javax.swing.JLabel();
        lbDrink = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbAdmin = new javax.swing.JLabel();
        body = new javax.swing.JPanel();
        Drink = new javax.swing.JPanel();
        dP1 = new javax.swing.JPanel();
        btNext = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        pIMocha = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        addIMocha = new javax.swing.JButton();
        qtyIMocha = new javax.swing.JSpinner();
        jLabel34 = new javax.swing.JLabel();
        pIGreenTea = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        addIGreenTea = new javax.swing.JButton();
        qtyIGreenTea = new javax.swing.JSpinner();
        pICappuccino = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        addICappuccino = new javax.swing.JButton();
        qtyICappuccino = new javax.swing.JSpinner();
        pILatte = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        addILatte = new javax.swing.JButton();
        qtyILatte = new javax.swing.JSpinner();
        pIAmericano = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        addIAmericano = new javax.swing.JButton();
        qtyIAmericano = new javax.swing.JSpinner();
        pHLatte = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        addHLatte = new javax.swing.JButton();
        qtyHLatte = new javax.swing.JSpinner();
        pHCappuccino = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        addHCappuccino = new javax.swing.JButton();
        qtyHCappuccino = new javax.swing.JSpinner();
        pHGreenTea = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        addHGreenTea = new javax.swing.JButton();
        qtyHGreenTea = new javax.swing.JSpinner();
        pHEspresso = new javax.swing.JPanel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        addHEspresso = new javax.swing.JButton();
        qtyHEspresso = new javax.swing.JSpinner();
        dP2 = new javax.swing.JPanel();
        btBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pFGreenTea = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        addFGreenTea = new javax.swing.JButton();
        qtyFGreenTea = new javax.swing.JSpinner();
        pSmoothie = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        addSmoothie = new javax.swing.JButton();
        qtySmoothie = new javax.swing.JSpinner();
        pFChocolate = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        addFChocolate = new javax.swing.JButton();
        qtyFChocolate = new javax.swing.JSpinner();
        Snack = new javax.swing.JPanel();
        sP1 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        pCroissant = new javax.swing.JPanel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        addCroissant = new javax.swing.JButton();
        qtyCroissant = new javax.swing.JSpinner();
        pPainauChocolat = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        addPainauChocolat = new javax.swing.JButton();
        qtyPainauChocolat = new javax.swing.JSpinner();
        pMatchaCake = new javax.swing.JPanel();
        jLabel87 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        addMatchaCake = new javax.swing.JButton();
        qtyMatchaCake = new javax.swing.JSpinner();
        right = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbSubtotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbDiscount = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        lbTotal = new javax.swing.JTextField();
        btTotal = new javax.swing.JButton();
        btDelete = new javax.swing.JButton();
        btSubtotal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1512, 982));
        getContentPane().setLayout(null);

        sidePanel.setBackground(new java.awt.Color(255, 255, 255));
        sidePanel.setLayout(null);

        btExit.setText("Exit");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });
        sidePanel.add(btExit);
        btExit.setBounds(40, 800, 72, 40);

        lbCake.setBackground(new java.awt.Color(255, 255, 255));
        lbCake.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        lbCake.setForeground(new java.awt.Color(51, 51, 51));
        lbCake.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCake.setText("Cake");
        lbCake.setToolTipText("");
        lbCake.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbCake.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbCake.setOpaque(true);
        lbCake.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCakeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbCakeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbCakeMouseExited(evt);
            }
        });
        sidePanel.add(lbCake);
        lbCake.setBounds(0, 260, 160, 70);

        lbDrink.setBackground(new java.awt.Color(255, 255, 255));
        lbDrink.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 14)); // NOI18N
        lbDrink.setForeground(new java.awt.Color(51, 51, 51));
        lbDrink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDrink.setText("Drink ");
        lbDrink.setToolTipText("");
        lbDrink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbDrink.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbDrink.setOpaque(true);
        lbDrink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDrinkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbDrinkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbDrinkMouseExited(evt);
            }
        });
        sidePanel.add(lbDrink);
        lbDrink.setBounds(0, 180, 160, 70);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logo.png"))); // NOI18N
        sidePanel.add(jLabel6);
        jLabel6.setBounds(20, 30, 120, 120);

        lbAdmin.setBackground(new java.awt.Color(255, 255, 255));
        lbAdmin.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 12)); // NOI18N
        lbAdmin.setForeground(new java.awt.Color(51, 51, 51));
        lbAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAdmin.setText("Admin");
        lbAdmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbAdmin.setOpaque(true);
        lbAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAdminMouseClicked(evt);
            }
        });
        sidePanel.add(lbAdmin);
        lbAdmin.setBounds(0, 750, 160, 40);

        getContentPane().add(sidePanel);
        sidePanel.setBounds(0, 0, 160, 980);

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new java.awt.CardLayout());

        Drink.setLayout(new java.awt.CardLayout());

        dP1.setBackground(new java.awt.Color(245, 245, 245));
        dP1.setLayout(null);

        btNext.setText("Next");
        btNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNextActionPerformed(evt);
            }
        });
        dP1.add(btNext);
        btNext.setBounds(610, 50, 78, 30);

        jLabel31.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jLabel31.setText("Drink");
        dP1.add(jLabel31);
        jLabel31.setBounds(30, 30, 70, 50);

        pIMocha.setBackground(new java.awt.Color(255, 255, 255));
        pIMocha.setLayout(null);

        jLabel38.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel38.setText("1.5$");
        pIMocha.add(jLabel38);
        jLabel38.setBounds(10, 180, 40, 16);

        jLabel39.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel39.setText("Iced Mocha");
        pIMocha.add(jLabel39);
        jLabel39.setBounds(10, 160, 120, 16);

        addIMocha.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addIMocha.setText("ADD");
        addIMocha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIMochaActionPerformed(evt);
            }
        });
        pIMocha.add(addIMocha);
        addIMocha.setBounds(130, 160, 60, 60);

        qtyIMocha.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pIMocha.add(qtyIMocha);
        qtyIMocha.setBounds(10, 200, 64, 20);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mocha.png"))); // NOI18N
        pIMocha.add(jLabel34);
        jLabel34.setBounds(20, 0, 150, 150);

        dP1.add(pIMocha);
        pIMocha.setBounds(490, 610, 200, 240);

        pIGreenTea.setBackground(new java.awt.Color(255, 255, 255));
        pIGreenTea.setLayout(null);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/greentea.png"))); // NOI18N
        pIGreenTea.add(jLabel32);
        jLabel32.setBounds(20, 0, 150, 150);

        jLabel33.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel33.setText("1.5$");
        pIGreenTea.add(jLabel33);
        jLabel33.setBounds(10, 180, 40, 16);

        jLabel40.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel40.setText("Iced Green Tea");
        pIGreenTea.add(jLabel40);
        jLabel40.setBounds(10, 160, 120, 16);

        addIGreenTea.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addIGreenTea.setText("ADD");
        addIGreenTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIGreenTeaActionPerformed(evt);
            }
        });
        pIGreenTea.add(addIGreenTea);
        addIGreenTea.setBounds(130, 160, 60, 60);

        qtyIGreenTea.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pIGreenTea.add(qtyIGreenTea);
        qtyIGreenTea.setBounds(10, 200, 64, 20);

        dP1.add(pIGreenTea);
        pIGreenTea.setBounds(260, 610, 200, 240);

        pICappuccino.setBackground(new java.awt.Color(255, 255, 255));
        pICappuccino.setLayout(null);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cappucino.png"))); // NOI18N
        pICappuccino.add(jLabel41);
        jLabel41.setBounds(20, 0, 150, 150);

        jLabel42.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel42.setText("2.0$");
        pICappuccino.add(jLabel42);
        jLabel42.setBounds(10, 180, 40, 16);

        jLabel43.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel43.setText("Iced Cappuccino");
        pICappuccino.add(jLabel43);
        jLabel43.setBounds(10, 160, 120, 16);

        addICappuccino.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addICappuccino.setText("ADD");
        addICappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addICappuccinoActionPerformed(evt);
            }
        });
        pICappuccino.add(addICappuccino);
        addICappuccino.setBounds(130, 160, 60, 60);

        qtyICappuccino.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pICappuccino.add(qtyICappuccino);
        qtyICappuccino.setBounds(10, 200, 64, 20);

        dP1.add(pICappuccino);
        pICappuccino.setBounds(30, 610, 200, 240);

        pILatte.setBackground(new java.awt.Color(255, 255, 255));
        pILatte.setLayout(null);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/latte.png"))); // NOI18N
        pILatte.add(jLabel44);
        jLabel44.setBounds(20, 0, 150, 150);

        jLabel45.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel45.setText("2.0$");
        pILatte.add(jLabel45);
        jLabel45.setBounds(10, 180, 40, 16);

        jLabel46.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel46.setText("Iced Latte");
        pILatte.add(jLabel46);
        jLabel46.setBounds(10, 160, 80, 16);

        addILatte.setText("ADD");
        addILatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addILatteActionPerformed(evt);
            }
        });
        pILatte.add(addILatte);
        addILatte.setBounds(130, 160, 60, 60);

        qtyILatte.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pILatte.add(qtyILatte);
        qtyILatte.setBounds(10, 200, 64, 20);

        dP1.add(pILatte);
        pILatte.setBounds(260, 350, 200, 240);

        pIAmericano.setBackground(new java.awt.Color(255, 255, 255));
        pIAmericano.setLayout(null);

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/americano.png"))); // NOI18N
        pIAmericano.add(jLabel47);
        jLabel47.setBounds(20, 0, 150, 140);

        jLabel48.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel48.setText("1.5$");
        pIAmericano.add(jLabel48);
        jLabel48.setBounds(10, 180, 40, 16);

        jLabel49.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel49.setText("Iced Americano");
        pIAmericano.add(jLabel49);
        jLabel49.setBounds(10, 160, 110, 16);

        addIAmericano.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addIAmericano.setText("ADD");
        addIAmericano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIAmericanoActionPerformed(evt);
            }
        });
        pIAmericano.add(addIAmericano);
        addIAmericano.setBounds(130, 160, 60, 60);

        qtyIAmericano.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pIAmericano.add(qtyIAmericano);
        qtyIAmericano.setBounds(10, 200, 64, 20);

        dP1.add(pIAmericano);
        pIAmericano.setBounds(490, 350, 200, 240);

        pHLatte.setBackground(new java.awt.Color(255, 255, 255));
        pHLatte.setLayout(null);

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hotlatte.png"))); // NOI18N
        pHLatte.add(jLabel50);
        jLabel50.setBounds(20, 0, 150, 150);

        jLabel51.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel51.setText("1,5$");
        pHLatte.add(jLabel51);
        jLabel51.setBounds(10, 180, 40, 16);

        jLabel52.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel52.setText("Hot Latte");
        pHLatte.add(jLabel52);
        jLabel52.setBounds(10, 160, 80, 16);

        addHLatte.setText("ADD");
        addHLatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHLatteActionPerformed(evt);
            }
        });
        pHLatte.add(addHLatte);
        addHLatte.setBounds(130, 160, 60, 60);

        qtyHLatte.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pHLatte.add(qtyHLatte);
        qtyHLatte.setBounds(10, 200, 64, 20);

        dP1.add(pHLatte);
        pHLatte.setBounds(30, 90, 200, 240);

        pHCappuccino.setBackground(new java.awt.Color(255, 255, 255));
        pHCappuccino.setLayout(null);

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hotcappu.png"))); // NOI18N
        pHCappuccino.add(jLabel53);
        jLabel53.setBounds(20, 0, 150, 150);

        jLabel54.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel54.setText("1.5$");
        pHCappuccino.add(jLabel54);
        jLabel54.setBounds(10, 180, 40, 16);

        jLabel55.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel55.setText("Hot Cappuccino");
        pHCappuccino.add(jLabel55);
        jLabel55.setBounds(10, 160, 120, 16);

        addHCappuccino.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addHCappuccino.setText("ADD");
        addHCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHCappuccinoActionPerformed(evt);
            }
        });
        pHCappuccino.add(addHCappuccino);
        addHCappuccino.setBounds(130, 160, 60, 60);

        qtyHCappuccino.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pHCappuccino.add(qtyHCappuccino);
        qtyHCappuccino.setBounds(10, 200, 64, 20);

        dP1.add(pHCappuccino);
        pHCappuccino.setBounds(490, 90, 200, 240);

        pHGreenTea.setBackground(new java.awt.Color(255, 255, 255));
        pHGreenTea.setLayout(null);

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/hotgreentea.png"))); // NOI18N
        pHGreenTea.add(jLabel56);
        jLabel56.setBounds(20, 0, 150, 150);

        jLabel57.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel57.setText("1.5$");
        pHGreenTea.add(jLabel57);
        jLabel57.setBounds(10, 180, 40, 16);

        jLabel58.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel58.setText("Hot Green Tea");
        pHGreenTea.add(jLabel58);
        jLabel58.setBounds(10, 160, 120, 16);

        addHGreenTea.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addHGreenTea.setText("ADD");
        addHGreenTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHGreenTeaActionPerformed(evt);
            }
        });
        pHGreenTea.add(addHGreenTea);
        addHGreenTea.setBounds(130, 160, 60, 60);

        qtyHGreenTea.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pHGreenTea.add(qtyHGreenTea);
        qtyHGreenTea.setBounds(10, 200, 64, 20);

        dP1.add(pHGreenTea);
        pHGreenTea.setBounds(30, 350, 200, 240);

        pHEspresso.setBackground(new java.awt.Color(255, 255, 255));
        pHEspresso.setLayout(null);

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/espresso.png"))); // NOI18N
        pHEspresso.add(jLabel59);
        jLabel59.setBounds(20, 0, 150, 150);

        jLabel60.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel60.setText("1.0$");
        pHEspresso.add(jLabel60);
        jLabel60.setBounds(10, 180, 40, 16);

        jLabel61.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel61.setText("Hot Espresso");
        pHEspresso.add(jLabel61);
        jLabel61.setBounds(10, 160, 110, 16);

        addHEspresso.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addHEspresso.setText("ADD");
        addHEspresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHEspressoActionPerformed(evt);
            }
        });
        pHEspresso.add(addHEspresso);
        addHEspresso.setBounds(130, 160, 60, 60);

        qtyHEspresso.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pHEspresso.add(qtyHEspresso);
        qtyHEspresso.setBounds(10, 200, 64, 20);

        dP1.add(pHEspresso);
        pHEspresso.setBounds(260, 90, 200, 240);

        Drink.add(dP1, "card2");

        dP2.setBackground(new java.awt.Color(245, 245, 245));
        dP2.setLayout(null);

        btBack.setText("Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });
        dP2.add(btBack);
        btBack.setBounds(610, 50, 78, 30);

        jLabel1.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jLabel1.setText("Drink");
        dP2.add(jLabel1);
        jLabel1.setBounds(30, 30, 70, 50);

        pFGreenTea.setBackground(new java.awt.Color(255, 255, 255));
        pFGreenTea.setLayout(null);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/greenteafrappe.png"))); // NOI18N
        pFGreenTea.add(jLabel25);
        jLabel25.setBounds(20, 0, 150, 150);

        jLabel26.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel26.setText("2,5$");
        pFGreenTea.add(jLabel26);
        jLabel26.setBounds(10, 180, 40, 16);

        jLabel27.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel27.setText("Green Tea Frappe");
        pFGreenTea.add(jLabel27);
        jLabel27.setBounds(10, 160, 120, 16);

        addFGreenTea.setText("ADD");
        addFGreenTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFGreenTeaActionPerformed(evt);
            }
        });
        pFGreenTea.add(addFGreenTea);
        addFGreenTea.setBounds(130, 160, 60, 60);

        qtyFGreenTea.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pFGreenTea.add(qtyFGreenTea);
        qtyFGreenTea.setBounds(10, 200, 64, 20);

        dP2.add(pFGreenTea);
        pFGreenTea.setBounds(30, 90, 200, 240);

        pSmoothie.setBackground(new java.awt.Color(255, 255, 255));
        pSmoothie.setLayout(null);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/berrysmoothie.png"))); // NOI18N
        pSmoothie.add(jLabel19);
        jLabel19.setBounds(20, 0, 150, 150);

        jLabel20.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel20.setText("3$");
        pSmoothie.add(jLabel20);
        jLabel20.setBounds(10, 180, 40, 16);

        jLabel21.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel21.setText("Berry Smoothie");
        pSmoothie.add(jLabel21);
        jLabel21.setBounds(10, 160, 120, 16);

        addSmoothie.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addSmoothie.setText("ADD");
        addSmoothie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSmoothieActionPerformed(evt);
            }
        });
        pSmoothie.add(addSmoothie);
        addSmoothie.setBounds(130, 160, 60, 60);

        qtySmoothie.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pSmoothie.add(qtySmoothie);
        qtySmoothie.setBounds(10, 200, 64, 20);

        dP2.add(pSmoothie);
        pSmoothie.setBounds(490, 90, 200, 240);

        pFChocolate.setBackground(new java.awt.Color(255, 255, 255));
        pFChocolate.setLayout(null);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/chocolatefrappe.png"))); // NOI18N
        pFChocolate.add(jLabel28);
        jLabel28.setBounds(20, 0, 150, 150);

        jLabel29.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel29.setText("2.5$");
        pFChocolate.add(jLabel29);
        jLabel29.setBounds(10, 180, 40, 16);

        jLabel30.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel30.setText("Chocolate Frappe");
        pFChocolate.add(jLabel30);
        jLabel30.setBounds(10, 160, 120, 16);

        addFChocolate.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addFChocolate.setText("ADD");
        addFChocolate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFChocolateActionPerformed(evt);
            }
        });
        pFChocolate.add(addFChocolate);
        addFChocolate.setBounds(130, 160, 60, 60);

        qtyFChocolate.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pFChocolate.add(qtyFChocolate);
        qtyFChocolate.setBounds(10, 200, 64, 20);

        dP2.add(pFChocolate);
        pFChocolate.setBounds(260, 90, 200, 240);

        Drink.add(dP2, "card2");

        body.add(Drink, "card2");

        Snack.setLayout(new java.awt.CardLayout());

        sP1.setBackground(new java.awt.Color(245, 245, 245));
        sP1.setLayout(null);

        jLabel62.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 24)); // NOI18N
        jLabel62.setText("Cake");
        sP1.add(jLabel62);
        jLabel62.setBounds(30, 30, 70, 50);

        pCroissant.setBackground(new java.awt.Color(255, 255, 255));
        pCroissant.setLayout(null);

        jLabel78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/croissant.png"))); // NOI18N
        pCroissant.add(jLabel78);
        jLabel78.setBounds(20, 0, 150, 150);

        jLabel79.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel79.setText("1,5$");
        pCroissant.add(jLabel79);
        jLabel79.setBounds(10, 180, 40, 16);

        jLabel80.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel80.setText("Croissant");
        pCroissant.add(jLabel80);
        jLabel80.setBounds(10, 160, 80, 16);

        addCroissant.setText("ADD");
        addCroissant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCroissantActionPerformed(evt);
            }
        });
        pCroissant.add(addCroissant);
        addCroissant.setBounds(130, 160, 60, 60);

        qtyCroissant.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pCroissant.add(qtyCroissant);
        qtyCroissant.setBounds(10, 200, 64, 20);

        sP1.add(pCroissant);
        pCroissant.setBounds(30, 90, 200, 240);

        pPainauChocolat.setBackground(new java.awt.Color(255, 255, 255));
        pPainauChocolat.setLayout(null);

        jLabel81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/painchocolat.png"))); // NOI18N
        pPainauChocolat.add(jLabel81);
        jLabel81.setBounds(20, 0, 150, 150);

        jLabel82.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel82.setText("1.5$");
        pPainauChocolat.add(jLabel82);
        jLabel82.setBounds(10, 180, 40, 16);

        jLabel83.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel83.setText("Pain au Chocolat");
        pPainauChocolat.add(jLabel83);
        jLabel83.setBounds(10, 160, 120, 16);

        addPainauChocolat.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addPainauChocolat.setText("ADD");
        addPainauChocolat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPainauChocolatActionPerformed(evt);
            }
        });
        pPainauChocolat.add(addPainauChocolat);
        addPainauChocolat.setBounds(130, 160, 60, 60);

        qtyPainauChocolat.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pPainauChocolat.add(qtyPainauChocolat);
        qtyPainauChocolat.setBounds(10, 200, 64, 20);

        sP1.add(pPainauChocolat);
        pPainauChocolat.setBounds(260, 90, 200, 240);

        pMatchaCake.setBackground(new java.awt.Color(255, 255, 255));
        pMatchaCake.setLayout(null);

        jLabel87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/matchacake.png"))); // NOI18N
        pMatchaCake.add(jLabel87);
        jLabel87.setBounds(20, 0, 150, 150);

        jLabel88.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel88.setText("3.5$");
        pMatchaCake.add(jLabel88);
        jLabel88.setBounds(10, 180, 40, 16);

        jLabel89.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 13)); // NOI18N
        jLabel89.setText("Matcha Cake");
        pMatchaCake.add(jLabel89);
        jLabel89.setBounds(10, 160, 110, 16);

        addMatchaCake.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        addMatchaCake.setText("ADD");
        addMatchaCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMatchaCakeActionPerformed(evt);
            }
        });
        pMatchaCake.add(addMatchaCake);
        addMatchaCake.setBounds(130, 160, 60, 60);

        qtyMatchaCake.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        pMatchaCake.add(qtyMatchaCake);
        qtyMatchaCake.setBounds(10, 200, 64, 20);

        sP1.add(pMatchaCake);
        pMatchaCake.setBounds(490, 90, 200, 240);

        Snack.add(sP1, "card2");

        body.add(Snack, "card2");

        getContentPane().add(body);
        body.setBounds(160, 0, 750, 980);

        right.setBackground(new java.awt.Color(255, 255, 255));
        right.setLayout(null);

        table.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 12)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product", "Price", "Qty", "Customization", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table);

        right.add(jScrollPane2);
        jScrollPane2.setBounds(10, 20, 580, 390);

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(null);

        jLabel3.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        jLabel3.setText("Discount: ");
        jPanel17.add(jLabel3);
        jLabel3.setBounds(20, 60, 130, 30);

        lbSubtotal.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        lbSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbSubtotalActionPerformed(evt);
            }
        });
        jPanel17.add(lbSubtotal);
        lbSubtotal.setBounds(160, 10, 190, 30);

        jLabel4.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        jLabel4.setText("Subtotal: ");
        jPanel17.add(jLabel4);
        jLabel4.setBounds(20, 10, 119, 30);

        cbDiscount.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        cbDiscount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0%", "30%", "50%", "70%" }));
        cbDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDiscountActionPerformed(evt);
            }
        });
        jPanel17.add(cbDiscount);
        cbDiscount.setBounds(160, 60, 190, 30);

        jLabel5.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        jLabel5.setText("Total:");
        jPanel17.add(jLabel5);
        jLabel5.setBounds(20, 110, 59, 25);

        lbTotal.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 18)); // NOI18N
        lbTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbTotalActionPerformed(evt);
            }
        });
        jPanel17.add(lbTotal);
        lbTotal.setBounds(160, 110, 190, 28);

        right.add(jPanel17);
        jPanel17.setBounds(20, 430, 370, 150);

        btTotal.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        btTotal.setText("Total");
        btTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTotalActionPerformed(evt);
            }
        });
        right.add(btTotal);
        btTotal.setBounds(190, 620, 130, 40);

        btDelete.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        btDelete.setText("Delete");
        btDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleteActionPerformed(evt);
            }
        });
        right.add(btDelete);
        btDelete.setBounds(430, 440, 130, 30);

        btSubtotal.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 20)); // NOI18N
        btSubtotal.setText("Subtotal");
        btSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubtotalActionPerformed(evt);
            }
        });
        right.add(btSubtotal);
        btSubtotal.setBounds(40, 620, 130, 40);

        getContentPane().add(right);
        right.setBounds(910, 0, 600, 980);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbCakeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCakeMouseClicked
        body.removeAll();
        body.add(Snack);
        body.revalidate();
        body.repaint();
    }//GEN-LAST:event_lbCakeMouseClicked

    private void lbDrinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDrinkMouseClicked
        body.removeAll();
        body.add(Drink);
        body.revalidate();
        body.repaint();
    }//GEN-LAST:event_lbDrinkMouseClicked

    private void lbDrinkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDrinkMouseExited
        lbDrink.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_lbDrinkMouseExited

    private void lbDrinkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDrinkMouseEntered
        lbDrink.setBackground(new Color(229,214,192));
    }//GEN-LAST:event_lbDrinkMouseEntered

    private void lbCakeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCakeMouseEntered
        lbCake.setBackground(new Color(229,214,192));
    }//GEN-LAST:event_lbCakeMouseEntered

    private void lbCakeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCakeMouseExited
        lbCake.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_lbCakeMouseExited

    private void lbSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbSubtotalActionPerformed

    private void lbTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lbTotalActionPerformed

    private void btDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        int selectedRow = table.getSelectedRow();

        // 1. Check if the user actually clicked a row
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select an item to delete.", "Delete Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. Remove from the Logic (Order.java)
        // IMPORTANT: This must happen while the indexes still match!
        currentOrder.removeProduct(selectedRow);

        // 3. Remove from the View (JTable)
        model.removeRow(selectedRow);

        // Optional: Clear the Total label since the previous total is now wrong
        lbTotal.setText(""); 
    }//GEN-LAST:event_btDeleteActionPerformed

    private void btTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTotalActionPerformed
        // 1. Ask Order logic for the final price (it automatically applies the discount)
        double finalTotal = currentOrder.calculateTotal();

        // 2. Display it
        lbTotal.setText(String.format("$%.2f", finalTotal));

        // 3. Ask for Payment Confirmation
        int choice = JOptionPane.showConfirmDialog(this, 
                "Total Amount: " + String.format("$%.2f", finalTotal) + "\nProceed to payment?", 
                "Checkout", 
                JOptionPane.YES_NO_OPTION);

        // 4. If Yes, Save to Database
        if (choice == JOptionPane.YES_OPTION) {
            controller.saveOrderToDatabase(finalTotal);
        }
    }//GEN-LAST:event_btTotalActionPerformed

    private void cbDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDiscountActionPerformed
        // Get the selected discount percentage from the ComboBox
        String selectedDiscount = (String)cbDiscount.getSelectedItem();

        double discountPercentage;
            // Adjust based on selection
            discountPercentage = switch (selectedDiscount) {
                case "0%"  -> 0.0;
                case "30%" -> 30.0;
                case "50%" -> 50.0;
                case "70%" -> 70.0;
                default -> 0.0;
            };
        // Set the discount for the current order
        currentOrder.setDiscount(discountPercentage);
    }//GEN-LAST:event_cbDiscountActionPerformed

    private void addSmoothieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSmoothieActionPerformed
        controller.addToCart("D12", qtySmoothie);
    }//GEN-LAST:event_addSmoothieActionPerformed

    private void addFGreenTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFGreenTeaActionPerformed
        controller.addToCart("D10", qtyFGreenTea);
    }//GEN-LAST:event_addFGreenTeaActionPerformed

    private void addFChocolateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFChocolateActionPerformed
        controller.addToCart("D11", qtyFChocolate);
    }//GEN-LAST:event_addFChocolateActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btExitActionPerformed
 
    public javax.swing.JTable getTable() {
        return table;
    }

    public javax.swing.JTextField getLbTotal() {
        return lbTotal;
    }

    public javax.swing.JTextField getLbSubtotal() {
        return lbSubtotal;
    }
    
    private void btSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubtotalActionPerformed
        // 1. Ask the Order logic to sum up the products
        double sub = currentOrder.calculateSubtotal();

        // 2. Update the Subtotal text field
        lbSubtotal.setText(String.format("$%.2f", sub));
    }//GEN-LAST:event_btSubtotalActionPerformed

    private void lbAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAdminMouseClicked
        Admin​ ad = new Admin();
        ad.setVisible(true);
    }//GEN-LAST:event_lbAdminMouseClicked

    private void addHLatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHLatteActionPerformed
        controller.addToCart("D01", qtyHLatte);
    }//GEN-LAST:event_addHLatteActionPerformed

    private void addHCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHCappuccinoActionPerformed
        controller.addToCart("D03", qtyHCappuccino);
    }//GEN-LAST:event_addHCappuccinoActionPerformed

    private void addHGreenTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHGreenTeaActionPerformed
        controller.addToCart("D04", qtyHGreenTea);
    }//GEN-LAST:event_addHGreenTeaActionPerformed

    private void addHEspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHEspressoActionPerformed
        controller.addToCart("D02", qtyHEspresso);
    }//GEN-LAST:event_addHEspressoActionPerformed

    private void btNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNextActionPerformed
        Drink.removeAll();
        Drink.add(dP2);
        Drink.revalidate();
        Drink.repaint();
    }//GEN-LAST:event_btNextActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        Drink.removeAll();
        Drink.add(dP1);
        Drink.revalidate();
        Drink.repaint(); 
    }//GEN-LAST:event_btBackActionPerformed

    private void addIAmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIAmericanoActionPerformed
        controller.addToCart("D06", qtyIAmericano);
    }//GEN-LAST:event_addIAmericanoActionPerformed

    private void addILatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addILatteActionPerformed
        controller.addToCart("D05", qtyILatte);
    }//GEN-LAST:event_addILatteActionPerformed

    private void addICappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addICappuccinoActionPerformed
        controller.addToCart("D07", qtyICappuccino);
    }//GEN-LAST:event_addICappuccinoActionPerformed

    private void addIGreenTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIGreenTeaActionPerformed
        controller.addToCart("D08", qtyIGreenTea);
    }//GEN-LAST:event_addIGreenTeaActionPerformed

    private void addIMochaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIMochaActionPerformed
        controller.addToCart("D09", qtyIMocha);
    }//GEN-LAST:event_addIMochaActionPerformed

    private void addMatchaCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMatchaCakeActionPerformed
        controller.addToCart("S03", qtyMatchaCake);
    }//GEN-LAST:event_addMatchaCakeActionPerformed

    private void addPainauChocolatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPainauChocolatActionPerformed
        controller.addToCart("S02", qtyPainauChocolat);
    }//GEN-LAST:event_addPainauChocolatActionPerformed

    private void addCroissantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCroissantActionPerformed
        controller.addToCart("S01", qtyCroissant);
    }//GEN-LAST:event_addCroissantActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Drink;
    private javax.swing.JPanel Snack;
    private javax.swing.JButton addCroissant;
    private javax.swing.JButton addFChocolate;
    private javax.swing.JButton addFGreenTea;
    private javax.swing.JButton addHCappuccino;
    private javax.swing.JButton addHEspresso;
    private javax.swing.JButton addHGreenTea;
    private javax.swing.JButton addHLatte;
    private javax.swing.JButton addIAmericano;
    private javax.swing.JButton addICappuccino;
    private javax.swing.JButton addIGreenTea;
    private javax.swing.JButton addILatte;
    private javax.swing.JButton addIMocha;
    private javax.swing.JButton addMatchaCake;
    private javax.swing.JButton addPainauChocolat;
    private javax.swing.JButton addSmoothie;
    private javax.swing.JPanel body;
    private javax.swing.JButton btBack;
    private javax.swing.JButton btDelete;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btNext;
    private javax.swing.JButton btSubtotal;
    private javax.swing.JButton btTotal;
    private javax.swing.JComboBox<String> cbDiscount;
    private javax.swing.JPanel dP1;
    private javax.swing.JPanel dP2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAdmin;
    private javax.swing.JLabel lbCake;
    private javax.swing.JLabel lbDrink;
    private javax.swing.JTextField lbSubtotal;
    private javax.swing.JTextField lbTotal;
    private javax.swing.JPanel pCroissant;
    private javax.swing.JPanel pFChocolate;
    private javax.swing.JPanel pFGreenTea;
    private javax.swing.JPanel pHCappuccino;
    private javax.swing.JPanel pHEspresso;
    private javax.swing.JPanel pHGreenTea;
    private javax.swing.JPanel pHLatte;
    private javax.swing.JPanel pIAmericano;
    private javax.swing.JPanel pICappuccino;
    private javax.swing.JPanel pIGreenTea;
    private javax.swing.JPanel pILatte;
    private javax.swing.JPanel pIMocha;
    private javax.swing.JPanel pMatchaCake;
    private javax.swing.JPanel pPainauChocolat;
    private javax.swing.JPanel pSmoothie;
    private javax.swing.JSpinner qtyCroissant;
    private javax.swing.JSpinner qtyFChocolate;
    private javax.swing.JSpinner qtyFGreenTea;
    private javax.swing.JSpinner qtyHCappuccino;
    private javax.swing.JSpinner qtyHEspresso;
    private javax.swing.JSpinner qtyHGreenTea;
    private javax.swing.JSpinner qtyHLatte;
    private javax.swing.JSpinner qtyIAmericano;
    private javax.swing.JSpinner qtyICappuccino;
    private javax.swing.JSpinner qtyIGreenTea;
    private javax.swing.JSpinner qtyILatte;
    private javax.swing.JSpinner qtyIMocha;
    private javax.swing.JSpinner qtyMatchaCake;
    private javax.swing.JSpinner qtyPainauChocolat;
    private javax.swing.JSpinner qtySmoothie;
    private javax.swing.JPanel right;
    private javax.swing.JPanel sP1;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
